const dbCz = [
  { id: 1, cz: 'Jsem [йсем]', ua: 'Я є', context: '', association: '' },
  { id: 2, cz: 'Ty jsi [ти йсі]', ua: 'Ти є', context: '', association: '' },
  { id: 3, cz: 'On je [он йє]', ua: 'Він є', context: '', association: '' },
  { id: 4, cz: 'Ona je [она йє]', ua: 'Вона є', context: '', association: '' },
  { id: 5, cz: 'My jsme [ми йсме]', ua: 'Ми є', context: '', association: '' },
  { id: 6, cz: 'Vy jste [ви йсте]', ua: 'Ви є', context: '', association: '' },
  { id: 7, cz: 'Jít [йіт]', ua: 'Йти', context: '', association: '' },
  { id: 8, cz: 'Mít [міт]', ua: 'Мати', context: '', association: '' },
  { id: 9, cz: 'Vědět [вьє́дєт]', ua: 'Знати', context: '', association: '' },
  { id: 10, cz: 'Jíst [йіст]', ua: 'Їсти', context: '', association: '' },
  { id: 11, cz: 'Pít [піт]', ua: 'Пити', context: '', association: '' },
  {
    id: 12,
    cz: 'Milovat [мі́ловат]',
    ua: 'Любити',
    context: '',
    association: '',
  },
  { id: 13, cz: 'Vidět [ві́дьєт]', ua: 'Бачити', context: '', association: '' },
  { id: 14, cz: 'Číst [чіст]', ua: 'Читати', context: '', association: '' },
  { id: 15, cz: 'Psát [псат]', ua: 'Писати', context: '', association: '' },
  {
    id: 16,
    cz: 'Mluvit [млу́віт]',
    ua: 'Говорити',
    context: '',
    association: '',
  },
  {
    id: 17,
    cz: 'Rozumět [розу́мньєт]',
    ua: 'Розуміти',
    context: '',
    association: '',
  },
  { id: 18, cz: 'Chtít [хт’іт]', ua: 'Хотіти', context: '', association: '' },
  {
    id: 19,
    cz: 'Potřebovat [потрже́боват]',
    ua: 'Потребувати',
    context: '',
    association: '',
  },
  { id: 20, cz: 'Moci [мо́ці]', ua: 'Могти', context: '', association: '' },
  { id: 21, cz: 'Muset [му́сет]', ua: 'Мусити', context: '', association: '' },
  {
    id: 22,
    cz: 'Ptát se [пта́т се]',
    ua: 'Питати',
    context: '',
    association: '',
  },
  {
    id: 23,
    cz: 'Odpovědět [одпо́вьєдьєт]',
    ua: 'Відповідати',
    context: '',
    association: '',
  },
  { id: 24, cz: 'Hledat [хлє́дат]', ua: 'Шукати', context: '', association: '' },
  { id: 25, cz: 'Najít [найіт]', ua: 'Знайти', context: '', association: '' },
  { id: 26, cz: 'Vesnice [вє́сніцє]', ua: 'Село', context: '', association: '' },
  { id: 27, cz: 'Dům [дум]', ua: 'Дім', context: '', association: '' },
  { id: 28, cz: 'Byt [біт]', ua: 'Квартира', context: '', association: '' },
  {
    id: 29,
    cz: 'Univerzita [уні́верзіта]',
    ua: 'Університет',
    context: '',
    association: '',
  },
  { id: 30, cz: 'Obchod [о́бход]', ua: 'Магазин', context: '', association: '' },
  { id: 31, cz: 'Trh [трг]', ua: 'Ринок', context: '', association: '' },
  {
    id: 32,
    cz: 'Letadlo [лєта́дло]',
    ua: 'Літак',
    context: '',
    association: '',
  },
  { id: 33, cz: 'Letět [лє́тьєт]', ua: 'Летіти', context: '', association: '' },
  {
    id: 34,
    cz: 'Přijít [пржийіт]',
    ua: 'Прийти',
    context: '',
    association: '',
  },
  { id: 35, cz: 'Odejít [одє́йіт]', ua: 'Піти', context: '', association: '' },
  { id: 36, cz: 'Sedět [сє́дьєт]', ua: 'Сидіти', context: '', association: '' },
  { id: 37, cz: 'Ležet [ле́жєт]', ua: 'Лежати', context: '', association: '' },
  { id: 38, cz: 'Běžet [б’є́жєт]', ua: 'Бігти', context: '', association: '' },
  {
    id: 39,
    cz: 'Hrát si [гра́т сі]',
    ua: 'Гратися',
    context: '',
    association: '',
  },
  { id: 40, cz: 'Noviny [но́вінї]', ua: 'Газета', context: '', association: '' },
  {
    id: 41,
    cz: 'Časopis [ча́сопіс]',
    ua: 'Журнал',
    context: '',
    association: '',
  },
  {
    id: 42,
    cz: 'Televize [тєлєві́зє]',
    ua: 'Телевізор',
    context: '',
    association: '',
  },
  { id: 43, cz: 'Pití [піт’ї́]', ua: 'Напій', context: '', association: '' },
  {
    id: 44,
    cz: 'Snídaně [снї́данє]',
    ua: 'Сніданок',
    context: '',
    association: '',
  },
  {
    id: 45,
    cz: 'Večeře [вєче́рже]',
    ua: 'Вечеря',
    context: '',
    association: '',
  },
  { id: 46, cz: 'Dítě [дї́тє]', ua: 'Дитина', context: '', association: '' },
  { id: 47, cz: 'Přítel [пржї́тєл]', ua: 'Друг', context: '', association: '' },
  {
    id: 48,
    cz: 'Přítelkyně [пржї́тєлкінє]',
    ua: 'Подруга',
    context: '',
    association: '',
  },
  { id: 49, cz: 'Rodiče [ро́дічє]', ua: 'Батьки', context: '', association: '' },
  { id: 50, cz: 'Bratr [бра́тр]', ua: 'Брат', context: '', association: '' },
  { id: 51, cz: 'Dcera [дце́ра]', ua: 'Дочка', context: '', association: '' },
  {
    id: 52,
    cz: 'Krátký [кра́ткі]',
    ua: 'Короткий',
    context: '',
    association: '',
  },
  {
    id: 53,
    cz: 'Šťastný [шчя́стни]',
    ua: 'Щасливий',
    context: '',
    association: '',
  },
  { id: 54, cz: 'Smutný [сму́тни]', ua: 'Сумний', context: '', association: '' },
  { id: 55, cz: 'Chudý [худі]', ua: 'Бідний', context: '', association: '' },
  { id: 56, cz: 'Láska [ла́ска]', ua: 'Любов', context: '', association: '' },
  { id: 57, cz: 'Štěstí [шчє́сті]', ua: 'Щастя', context: '', association: '' },
  { id: 58, cz: 'Smrt [смерт]', ua: 'Смерть', context: '', association: '' },
  { id: 59, cz: 'Život [жї́вот]', ua: 'Життя', context: '', association: '' },
  {
    id: 60,
    cz: 'Přátelství [пржа́тєлстві]',
    ua: 'Дружба',
    context: '',
    association: '',
  },
  { id: 61, cz: 'Nebe [не́бе]', ua: 'Небо', context: '', association: '' },
  { id: 62, cz: 'Země [зє́мє]', ua: 'Земля', context: '', association: '' },
  { id: 63, cz: 'Měsíc [мьєсі́ц]', ua: 'Місяць', context: '', association: '' },
  { id: 64, cz: 'Hvězda [хвьє́зда]', ua: 'Зірка', context: '', association: '' },
  { id: 65, cz: 'Oheň [о́гень]', ua: 'Вогонь', context: '', association: '' },
  {
    id: 66,
    cz: 'Světlo [свьє́тло]',
    ua: 'Світло',
    context: '',
    association: '',
  },
  { id: 67, cz: 'Dnes [днєс]', ua: 'Сьогодні', context: '', association: '' },
  { id: 68, cz: 'Zítra [зї́тра]', ua: 'Завтра', context: '', association: '' },
  { id: 69, cz: 'Včera [вчє́ра]', ua: 'Вчора', context: '', association: '' },
  {
    id: 70,
    cz: 'Studený [студєни]',
    ua: 'Холодний',
    context: '',
    association: '',
  },
  { id: 71, cz: 'Těžký [тєжки]', ua: 'Важкий', context: '', association: '' },
  { id: 72, cz: 'Jasný [ясни]', ua: 'Ясний', context: '', association: '' },
  { id: 73, cz: 'Oblaka [облака]', ua: 'Хмари', context: '', association: '' },
  {
    id: 74,
    cz: 'Vichřice [вї́хріцє]',
    ua: 'Вітер',
    context: '',
    association: '',
  },
  { id: 75, cz: 'Bouře [бо́уже]', ua: 'Буря', context: '', association: '' },
  { id: 76, cz: 'Horko [горко]', ua: 'Спека', context: '', association: '' },
  {
    id: 77,
    cz: 'Přítomnost [пржї́томност]',
    ua: 'Сьогодення',
    context: '',
    association: '',
  },
  {
    id: 78,
    cz: 'Minulost [минулост]',
    ua: 'Минуле',
    context: '',
    association: '',
  },
  {
    id: 79,
    cz: 'Budoucnost [будоуцност]',
    ua: 'Майбутнє',
    context: '',
    association: '',
  },
  { id: 80, cz: 'Někdo [нєкдо]', ua: 'Хтось', context: '', association: '' },
  { id: 81, cz: 'Nikdo [нікдо]', ua: 'Ніхто', context: '', association: '' },
  { id: 82, cz: 'Něco [нєцо]', ua: 'Щось', context: '', association: '' },
  { id: 83, cz: 'Jen [йєн]', ua: 'Лише', context: '', association: '' },
  { id: 84, cz: 'Jako [я́ко]', ua: 'Як', context: '', association: '' },
  {
    id: 85,
    cz: 'Protože [прото́же]',
    ua: 'Тому що',
    context: '',
    association: '',
  },
  { id: 86, cz: 'Proč [про́ч]', ua: 'Чому', context: '', association: '' },
  { id: 87, cz: 'Kdy [гди]', ua: 'Коли', context: '', association: '' },
  { id: 88, cz: 'Odkud [одкуд]', ua: 'Звідки', context: '', association: '' },
  { id: 89, cz: 'Kdyby [гдиби]', ua: 'Якби', context: '', association: '' },
  { id: 90, cz: 'Před [пржєд]', ua: 'Перед', context: '', association: '' },
  { id: 91, cz: 'Mezi [мєзі]', ua: 'Між', context: '', association: '' },
  { id: 92, cz: 'Kromě [кроме]', ua: 'Крім', context: '', association: '' },
  {
    id: 93,
    cz: 'Zaměstnání [замнє́стнани]',
    ua: 'Працевлаштування',
    context: '',
    association: '',
  },
  {
    id: 94,
    cz: 'Zaměstnanec [замнє́стнанєц]',
    ua: 'Працівник',
    context: '',
    association: '',
  },
  { id: 95, cz: 'Šéf [ше́ф]', ua: 'Начальник', context: '', association: '' },
  { id: 96, cz: 'Plat [плат]', ua: 'Зарплата', context: '', association: '' },
  {
    id: 97,
    cz: 'Kancelář [канцела́рш]',
    ua: 'Офіс',
    context: '',
    association: '',
  },
  {
    id: 98,
    cz: 'Schůzka [сху́зка]',
    ua: 'Зустріч',
    context: '',
    association: '',
  },
  { id: 99, cz: 'Tým [тїм]', ua: 'Команда', context: '', association: '' },
];

export default dbCz;

// const dbCz = [];
