const dbCz = [
  { id: 1, cz: 'Jít [йіт]', ua: 'Йти', context: '', association: '' },
  { id: 2, cz: 'Mít [міт]', ua: 'Мати', context: '', association: '' },
  { id: 3, cz: 'Vědět [вьє́дєт]', ua: 'Знати', context: '', association: '' },
  { id: 4, cz: 'Jíst [йіст]', ua: 'Їсти', context: '', association: '' },
  { id: 5, cz: 'Pít [піт]', ua: 'Пити', context: '', association: '' },
  {
    id: 6,
    cz: 'Milovat [мі́ловат]',
    ua: 'Любити',
    context: '',
    association: '',
  },
  { id: 7, cz: 'Vidět [ві́дьєт]', ua: 'Бачити', context: '', association: '' },
  { id: 8, cz: 'Číst [чіст]', ua: 'Читати', context: '', association: '' },
  { id: 9, cz: 'Psát [псат]', ua: 'Писати', context: '', association: '' },
  {
    id: 10,
    cz: 'Mluvit [млу́віт]',
    ua: 'Говорити',
    context: '',
    association: '',
  },
  {
    id: 11,
    cz: 'Rozumět [розу́мньєт]',
    ua: 'Розуміти',
    context: '',
    association: '',
  },
  { id: 12, cz: 'Chtít [хт’іт]', ua: 'Хотіти', context: '', association: '' },
  {
    id: 13,
    cz: 'Potřebovat [потрже́боват]',
    ua: 'Потребувати',
    context: '',
    association: '',
  },
  { id: 14, cz: 'Moci [мо́ці]', ua: 'Могти', context: '', association: '' },
  { id: 15, cz: 'Muset [му́сет]', ua: 'Мусити', context: '', association: '' },
  {
    id: 16,
    cz: 'Ptát se [пта́т се]',
    ua: 'Питати',
    context: '',
    association: '',
  },
  {
    id: 17,
    cz: 'Odpovědět [одпо́вьєдьєт]',
    ua: 'Відповідати',
    context: '',
    association: '',
  },
  { id: 18, cz: 'Hledat [хлє́дат]', ua: 'Шукати', context: '', association: '' },
  { id: 19, cz: 'Najít [найіт]', ua: 'Знайти', context: '', association: '' },
  { id: 20, cz: 'Vesnice [вє́сніцє]', ua: 'Село', context: '', association: '' },
  { id: 21, cz: 'Dům [дум]', ua: 'Дім', context: '', association: '' },
  { id: 22, cz: 'Byt [біт]', ua: 'Квартира', context: '', association: '' },
  {
    id: 23,
    cz: 'Univerzita [уні́верзіта]',
    ua: 'Університет',
    context: '',
    association: '',
  },
  { id: 24, cz: 'Obchod [о́бход]', ua: 'Магазин', context: '', association: '' },
  { id: 25, cz: 'Trh [трг]', ua: 'Ринок', context: '', association: '' },
  {
    id: 26,
    cz: 'Letadlo [лєта́дло]',
    ua: 'Літак',
    context: '',
    association: '',
  },
  { id: 27, cz: 'Letět [лє́тьєт]', ua: 'Летіти', context: '', association: '' },
  {
    id: 28,
    cz: 'Přijít [пржийіт]',
    ua: 'Прийти',
    context: '',
    association: '',
  },
  { id: 29, cz: 'Odejít [одє́йіт]', ua: 'Піти', context: '', association: '' },
  { id: 30, cz: 'Sedět [сє́дьєт]', ua: 'Сидіти', context: '', association: '' },
  { id: 31, cz: 'Ležet [ле́жєт]', ua: 'Лежати', context: '', association: '' },
  { id: 32, cz: 'Běžet [б’є́жєт]', ua: 'Бігти', context: '', association: '' },
  {
    id: 33,
    cz: 'Hrát si [гра́т сі]',
    ua: 'Гратися',
    context: '',
    association: '',
  },
  { id: 34, cz: 'Noviny [но́вінї]', ua: 'Газета', context: '', association: '' },
  {
    id: 35,
    cz: 'Časopis [ча́сопіс]',
    ua: 'Журнал',
    context: '',
    association: '',
  },
  {
    id: 36,
    cz: 'Televize [тєлєві́зє]',
    ua: 'Телевізор',
    context: '',
    association: '',
  },
  { id: 37, cz: 'Pití [піт’ї́]', ua: 'Напій', context: '', association: '' },
  {
    id: 38,
    cz: 'Snídaně [снї́данє]',
    ua: 'Сніданок',
    context: '',
    association: '',
  },
  {
    id: 39,
    cz: 'Večeře [вєче́рже]',
    ua: 'Вечеря',
    context: '',
    association: '',
  },
  { id: 40, cz: 'Dítě [дї́тє]', ua: 'Дитина', context: '', association: '' },
  { id: 41, cz: 'Přítel [пржї́тєл]', ua: 'Друг', context: '', association: '' },
  {
    id: 42,
    cz: 'Přítelkyně [пржї́тєлкінє]',
    ua: 'Подруга',
    context: '',
    association: '',
  },
  { id: 43, cz: 'Rodiče [ро́дічє]', ua: 'Батьки', context: '', association: '' },
  { id: 44, cz: 'Dcera [дце́ра]', ua: 'Дочка', context: '', association: '' },
  {
    id: 45,
    cz: 'Krátký [кра́ткі]',
    ua: 'Короткий',
    context: '',
    association: '',
  },
  {
    id: 46,
    cz: 'Šťastný [шчя́стни]',
    ua: 'Щасливий',
    context: '',
    association: '',
  },
  { id: 47, cz: 'Smutný [сму́тни]', ua: 'Сумний', context: '', association: '' },
  { id: 48, cz: 'Chudý [худі]', ua: 'Бідний', context: '', association: '' },
  { id: 49, cz: 'Láska [ла́ска]', ua: 'Любов', context: '', association: '' },
  { id: 50, cz: 'Štěstí [шчє́сті]', ua: 'Щастя', context: '', association: '' },
  { id: 51, cz: 'Smrt [смерт]', ua: 'Смерть', context: '', association: '' },
  { id: 52, cz: 'Život [жї́вот]', ua: 'Життя', context: '', association: '' },
  {
    id: 53,
    cz: 'Přátelství [пржа́тєлстві]',
    ua: 'Дружба',
    context: '',
    association: '',
  },
  { id: 54, cz: 'Nebe [не́бе]', ua: 'Небо', context: '', association: '' },
  { id: 55, cz: 'Země [зє́мє]', ua: 'Земля', context: '', association: '' },
  { id: 56, cz: 'Měsíc [мьєсі́ц]', ua: 'Місяць', context: '', association: '' },
  { id: 57, cz: 'Hvězda [хвьє́зда]', ua: 'Зірка', context: '', association: '' },
  { id: 58, cz: 'Oheň [о́гень]', ua: 'Вогонь', context: '', association: '' },
  {
    id: 59,
    cz: 'Světlo [свьє́тло]',
    ua: 'Світло',
    context: '',
    association: '',
  },
  { id: 60, cz: 'Dnes [днєс]', ua: 'Сьогодні', context: '', association: '' },
  {
    id: 61,
    cz: 'Studený [студєни]',
    ua: 'Холодний',
    context: '',
    association: '',
  },
  { id: 62, cz: 'Těžký [тєжки]', ua: 'Важкий', context: '', association: '' },
  { id: 63, cz: 'Jasný [ясни]', ua: 'Ясний', context: '', association: '' },
  { id: 64, cz: 'Oblaka [облака]', ua: 'Хмари', context: '', association: '' },
  {
    id: 65,
    cz: 'Vichřice [вї́хріцє]',
    ua: 'Вітер',
    context: '',
    association: '',
  },
  { id: 66, cz: 'Horko [горко]', ua: 'Спека', context: '', association: '' },
  {
    id: 67,
    cz: 'Přítomnost [пржї́томност]',
    ua: 'Сьогодення',
    context: '',
    association: '',
  },
  {
    id: 68,
    cz: 'Minulost [минулост]',
    ua: 'Минуле',
    context: '',
    association: '',
  },
  {
    id: 69,
    cz: 'Budoucnost [будоуцност]',
    ua: 'Майбутнє',
    context: '',
    association: '',
  },
  { id: 70, cz: 'Někdo [нєкдо]', ua: 'Хтось', context: '', association: '' },
  { id: 71, cz: 'Nikdo [нікдо]', ua: 'Ніхто', context: '', association: '' },
  { id: 72, cz: 'Něco [нєцо]', ua: 'Щось', context: '', association: '' },
  { id: 73, cz: 'Jen [йєн]', ua: 'Лише', context: '', association: '' },
  { id: 74, cz: 'Kdy [гди]', ua: 'Коли', context: '', association: '' },
  { id: 75, cz: 'Odkud [одкуд]', ua: 'Звідки', context: '', association: '' },
  { id: 76, cz: 'Kdyby [гдиби]', ua: 'Якби', context: '', association: '' },
  { id: 77, cz: 'Před [пржєд]', ua: 'Перед', context: '', association: '' },
  { id: 78, cz: 'Mezi [мєзі]', ua: 'Між', context: '', association: '' },
  { id: 79, cz: 'Kromě [кроме]', ua: 'Крім', context: '', association: '' },
  {
    id: 80,
    cz: 'Zaměstnání [замнє́стнани]',
    ua: 'Працевлаштування',
    context: '',
    association: '',
  },
  {
    id: 81,
    cz: 'Zaměstnanec [замнє́стнанєц]',
    ua: 'Працівник',
    context: '',
    association: '',
  },
  { id: 82, cz: 'Šéf [ше́ф]', ua: 'Начальник', context: '', association: '' },
  { id: 83, cz: 'Plat [плат]', ua: 'Зарплата', context: '', association: '' },
  {
    id: 84,
    cz: 'Kancelář [канцела́рш]',
    ua: 'Офіс',
    context: '',
    association: '',
  },
  {
    id: 85,
    cz: 'Schůzka [сху́зка]',
    ua: 'Зустріч',
    context: '',
    association: '',
  },
  { id: 86, cz: 'Tým [тїм]', ua: 'Команда', context: '', association: '' },
  { id: 87, cz: 'Hádka [ха́дка]', ua: 'Сварка', context: '', association: '' },
  {
    id: 88,
    cz: 'Seznámili [сезна́мілі]',
    ua: 'Познайомилися',
    context: '',
    association: '',
  },
  { id: 89, cz: 'Důchod [ду́ход]', ua: 'Пенсія', context: '', association: '' },
  {
    id: 90,
    cz: 'Překvapení [пржеквапе́нї]',
    ua: 'Сюрприз',
    context: '',
    association: '',
  },
  {
    id: 91,
    cz: 'Jdi pryč [йді прич]',
    ua: 'Іди геть',
    context: '',
    association: '',
  },
  {
    id: 92,
    cz: 'Pozdravujte ho [поздра́вуйтє хо]',
    ua: 'Передавайте йому привіт',
    context: '',
    association: '',
  },
  {
    id: 93,
    cz: 'Potkal [по́ткал]',
    ua: 'Зустрів',
    context: '',
    association: '',
  },
  {
    id: 94,
    cz: 'Statečný [стате́чний]',
    ua: 'Хоробрий',
    context: '',
    association: '',
  },
  {
    id: 95,
    cz: 'Spolehlivý [споле́глївій]',
    ua: 'Надійний',
    context: '',
    association: '',
  },
  {
    id: 96,
    cz: 'Šikovný [шїко́вний]',
    ua: 'Вправний, талановитий',
    context: '',
    association: '',
  },
  { id: 97, cz: 'Kapsy [ка́пси]', ua: 'Кишені', context: '', association: '' },
  {
    id: 98,
    cz: 'Objednaly [обйе́днали]',
    ua: 'Замовили',
    context: '',
    association: '',
  },
  {
    id: 99,
    cz: 'Scházel se [сха́зел сє]',
    ua: 'Зустрічався',
    context: '',
    association: '',
  },
  {
    id: 100,
    cz: 'Podle jeho [по́дле є́го]',
    ua: 'За його словами',
    context: '',
    association: '',
  },
  {
    id: 101,
    cz: 'Pořád [пора́д]',
    ua: 'Постійно, завжди',
    context: '',
    association: '',
  },
  {
    id: 102,
    cz: 'Sloveso [сло́вєсо]',
    ua: 'Дієслово',
    context: '',
    association: '',
  },
  {
    id: 103,
    cz: 'Víme co to je [вїме́ цо то є]',
    ua: 'Ми знаємо, що це таке',
    context: '',
    association: '',
  },
  {
    id: 104,
    cz: 'Monterky [мо́нтерки]',
    ua: 'Робочий комбінезон',
    context: '',
    association: '',
  },
  {
    id: 105,
    cz: 'Deštník [де́штнік]',
    ua: 'Парасоля',
    context: '',
    association: '',
  },
  {
    id: 106,
    cz: 'Kartáček [ка́ртачек]',
    ua: 'Щіточка (зубна)',
    context: '',
    association: '',
  },
  {
    id: 107,
    cz: 'Co to znamená [цо то знаме́на]',
    ua: 'Що це означає',
    context: '',
    association: '',
  },
  { id: 108, cz: 'Bunda [бу́нда]', ua: 'Куртка', context: '', association: '' },
  { id: 109, cz: 'Kibl [кібл]', ua: 'Відро', context: '', association: '' },
  {
    id: 110,
    cz: 'Víte proč [вїтє про́ч]',
    ua: 'Знаєте чому',
    context: '',
    association: '',
  },
  {
    id: 111,
    cz: 'To je zajímavé [то є заї́маве]',
    ua: 'Це цікаво',
    context: '',
    association: '',
  },
  {
    id: 112,
    cz: 'To je náhoda [то є на́хода]',
    ua: 'Яка випадковість',
    context: '',
    association: '',
  },
  { id: 113, cz: 'Kam [кам]', ua: 'Куди', context: '', association: '' },
  {
    id: 114,
    cz: 'Prosím vás [про́сїм вас]',
    ua: 'Будь ласка (до вас)',
    context: '',
    association: '',
  },
  { id: 115, cz: 'Tohle [то́гле]', ua: 'Оце, це', context: '', association: '' },
  { id: 116, cz: 'Šipka [ші́пка]', ua: 'Стрілка', context: '', association: '' },
  {
    id: 117,
    cz: 'Odbočit [одбо́чіт]',
    ua: 'Звернути',
    context: '',
    association: '',
  },
  {
    id: 118,
    cz: 'Za kým jsem [за ким єсм]',
    ua: 'До кого я прийшов',
    context: '',
    association: '',
  },
  { id: 119, cz: 'Jeli [йєлі]', ua: 'Їхали', context: '', association: '' },
  {
    id: 120,
    cz: 'Navštívený [навшті́вєні]',
    ua: 'Відвіданий',
    context: '',
    association: '',
  },
  {
    id: 121,
    cz: 'Nabídnout [на́бїдноут]',
    ua: 'Запропонувати',
    context: '',
    association: '',
  },
  {
    id: 122,
    cz: 'Zjednodušit [зйєдноду́шіт]',
    ua: 'Спростити',
    context: '',
    association: '',
  },
  {
    id: 123,
    cz: 'Dám si šlofík [да́м сї шло́фїк]',
    ua: 'Трохи посплю, подрімати',
    context: '',
    association: '',
  },
  {
    id: 124,
    cz: 'Nápověda [на́повєда]',
    ua: 'Підказка',
    context: '',
    association: '',
  },
  {
    id: 125,
    cz: 'Furt [фурт]',
    ua: 'Постійно, завжди (розм.)',
    context: '',
    association: '',
  },
  {
    id: 126,
    cz: 'Vypadá [випа́да]',
    ua: 'Виглядає',
    context: '',
    association: '',
  },
  {
    id: 127,
    cz: 'Skutečný [ску́тєчни]',
    ua: 'Справжній, дійсний',
    context: '',
    association: '',
  },
  {
    id: 128,
    cz: 'V klidu [ф кліду]',
    ua: 'Спокійно',
    context: '',
    association: '',
  },
  {
    id: 129,
    cz: 'Počasí [по́часі]',
    ua: 'Погода',
    context: '',
    association: '',
  },
  {
    id: 130,
    cz: 'Sluší mi [слушї мі]',
    ua: 'Мені личить',
    context: '',
    association: '',
  },
  {
    id: 131,
    cz: 'Zdát se [зда́т сє]',
    ua: 'Здаватися',
    context: '',
    association: '',
  },
  {
    id: 132,
    cz: 'Doufám [до́уфам]',
    ua: 'Сподіваюся',
    context: '',
    association: '',
  },
  { id: 133, cz: 'Zboží [збо́жі]', ua: 'Товари', context: '', association: '' },
  {
    id: 134,
    cz: 'Použité [поу́жїтє]',
    ua: 'Використане',
    context: '',
    association: '',
  },
  {
    id: 135,
    cz: 'Kvůli [кву́лі]',
    ua: 'Через, заради',
    context: '',
    association: '',
  },
  { id: 136, cz: 'Hned [гнєд]', ua: 'Одразу', context: '', association: '' },
  {
    id: 137,
    cz: 'Dostáváme [доста́ваме]',
    ua: 'Ми отримуємо',
    context: '',
    association: '',
  },
  { id: 138, cz: 'Různě [ру́знє]', ua: 'Різні', context: '', association: '' },
  {
    id: 139,
    cz: 'Odložit [о́дложіт]',
    ua: 'Відкласти',
    context: '',
    association: '',
  },
  {
    id: 140,
    cz: 'Obsazeno [обса́зено]',
    ua: 'Зайнято',
    context: '',
    association: '',
  },
  {
    id: 141,
    cz: 'Trávit čas [тра́віт час]',
    ua: 'Проводити час',
    context: '',
    association: '',
  },
  {
    id: 142,
    cz: 'Přístup [пржі́ступ]',
    ua: 'Підхід',
    context: '',
    association: '',
  },
  {
    id: 143,
    cz: 'Přání [пржа́ні]',
    ua: 'Бажання, побажання',
    context: '',
    association: '',
  },
  {
    id: 144,
    cz: 'Náročný [на́ро́чни]',
    ua: 'Складний, вимогливий',
    context: '',
    association: '',
  },
  {
    id: 145,
    cz: 'Dělám si legraci [дєла́м сї легра́ці]',
    ua: 'Я жартую',
    context: '',
    association: '',
  },
  {
    id: 146,
    cz: 'Povolaný [повола́ни]',
    ua: 'Призначений, професія',
    context: '',
    association: '',
  },
  {
    id: 147,
    cz: 'Samozřejmě [само́зреймє]',
    ua: 'Звісно, само собою',
    context: '',
    association: '',
  },
  { id: 148, cz: 'Všude [вшуде]', ua: 'Скрізь', context: '', association: '' },
  {
    id: 149,
    cz: 'Zahnete [захнєтє]',
    ua: 'Ви звернете',
    context: '',
    association: '',
  },
  {
    id: 150,
    cz: 'Poprvé v životě [попрвє в жи́вотє]',
    ua: 'Вперше в житті',
    context: '',
    association: '',
  },
  {
    id: 151,
    cz: 'Asi [асі]',
    ua: 'Мабуть, приблизно',
    context: '',
    association: '',
  },
  {
    id: 152,
    cz: 'Krájet [кра́йєт]',
    ua: 'Різати',
    context: '',
    association: '',
  },
  {
    id: 153,
    cz: 'Doporučil [допору́чил]',
    ua: 'Рекомендував',
    context: '',
    association: '',
  },
  {
    id: 154,
    cz: 'Podíváme se [подіва́ме се]',
    ua: 'Подивимося',
    context: '',
    association: '',
  },
  { id: 155, cz: 'Vliv [влів]', ua: 'Вплив', context: '', association: '' },
  { id: 156, cz: 'Pokud [поукд]', ua: 'Якщо', context: '', association: '' },
  {
    id: 157,
    cz: 'Nějaký [нєякі]',
    ua: 'Якийсь, який-небудь',
    context: '',
    association: '',
  },
  {
    id: 158,
    cz: 'Nálada [на́лада]',
    ua: 'Настрій',
    context: '',
    association: '',
  },
  {
    id: 159,
    cz: 'Úloha [у́лоха]',
    ua: 'Завдання, роль',
    context: '',
    association: '',
  },
];

export default dbCz;

// const dbCz = [];
