const dbCz = [{ id: 1, en: 'Jsem [йсем] ', ua: ' Я є', context: '',  association: '',},
  { id: 2, en: 'Ty jsi [ти йсі] ', ua: ' Ти є', context: '',  association: '',},
  { id: 3, en: 'On je [он йє] ', ua: ' Він є', context: '',  association: '',},
  { id: 4, en: 'Ona je [она йє] ', ua: ' Вона є', context: '',  association: '',},
  { id: 5, en: 'My jsme [ми йсме] ', ua: ' Ми є', context: '',  association: '',},
  { id: 6, en: 'Vy jste [ви йсте] ', ua: ' Ви є', context: '',  association: '',},
  { id: 7, en: 'Jít [йіт] ', ua: ' Йти', context: '',  association: '',},
  { id: 8, en: 'Mít [міт] ', ua: ' Мати', context: '',  association: '',},
  { id: 9, en: 'Vědět [вьє́дєт] ', ua: ' Знати', context: '',  association: '',},
  { id: 10, en: 'Jíst [йіст] ', ua: ' Їсти', context: '',  association: '',},
  { id: 11, en: 'Pít [піт] ', ua: ' Пити', context: '',  association: '',},
  { id: 12, en: 'Milovat [мі́ловат] ', ua: ' Любити', context: '',  association: '',},
  { id: 13, en: 'Vidět [ві́дьєт] ', ua: ' Бачити', context: '',  association: '',},
  { id: 14, en: 'Číst [чіст] ', ua: ' Читати', context: '',  association: '',},
  { id: 15, en: 'Psát [псат] ', ua: ' Писати', context: '',  association: '',},
  { id: 16, en: 'Mluvit [млу́віт] ', ua: ' Говорити', context: '',  association: '',},
  { id: 17, en: 'Rozumět [розу́мньєт] ', ua: ' Розуміти', context: '',  association: '',},
  { id: 18, en: 'Chtít [хт’іт] ', ua: ' Хотіти', context: '',  association: '',},
  { id: 19, en: 'Potřebovat [потрже́боват] ', ua: ' Потребувати', context: '',  association: '',},
  { id: 20, en: 'Moci [мо́ці] ', ua: ' Могти', context: '',  association: '',},
  { id: 21, en: 'Muset [му́сет] ', ua: ' Мусити', context: '',  association: '',},
  { id: 22, en: 'Ptát se [пта́т се] ', ua: ' Питати', context: '',  association: '',},
  { id: 23, en: 'Odpovědět [одпо́вьєдьєт] ', ua: ' Відповідати', context: '',  association: '',},
  { id: 24, en: 'Hledat [хлє́дат] ', ua: ' Шукати', context: '',  association: '',},
  { id: 25, en: 'Najít [найіт] ', ua: ' Знайти', context: '',  association: '',},
  { id: 26, en: 'Vesnice [вє́сніцє] ', ua: ' Село', context: '',  association: '',},
  { id: 27, en: 'Dům [дум] ', ua: ' Дім', context: '',  association: '',},
  { id: 28, en: 'Byt [біт] ', ua: ' Квартира', context: '',  association: '',},
  { id: 29, en: 'Univerzita [уні́верзіта] ', ua: ' Університет', context: '',  association: '',},
  { id: 30, en: 'Obchod [о́бход] ', ua: ' Магазин', context: '',  association: '',},
  { id: 31, en: 'Trh [трг] ', ua: ' Ринок', context: '',  association: '',},
  { id: 32, en: 'Letadlo [лєта́дло] ', ua: ' Літак', context: '',  association: '',},
  { id: 33, en: 'Letět [лє́тьєт] ', ua: ' Летіти', context: '',  association: '',},
  { id: 34, en: 'Přijít [пржийіт] ', ua: ' Прийти', context: '',  association: '',},
  { id: 35, en: 'Odejít [одє́йіт] ', ua: ' Піти', context: '',  association: '',},
  { id: 36, en: 'Sedět [сє́дьєт] ', ua: ' Сидіти', context: '',  association: '',},
  { id: 37, en: 'Ležet [ле́жєт] ', ua: ' Лежати', context: '',  association: '',},
  { id: 38, en: 'Běžet [б’є́жєт] ', ua: ' Бігти', context: '',  association: '',},
  { id: 39, en: 'Hrát si [гра́т сі] ', ua: ' Гратися', context: '',  association: '',},
  { id: 40, en: 'Noviny [но́вінї] ', ua: ' Газета', context: '',  association: '',},
  { id: 41, en: 'Časopis [ча́сопіс] ', ua: ' Журнал', context: '',  association: '',},
  { id: 42, en: 'Televize [тєлєві́зє] ', ua: ' Телевізор', context: '',  association: '',},
  { id: 43, en: 'Počítač [по́чітатш] ', ua: ' Комп'ютер', context: '',  association: '',},
  { id: 44, en: 'Pití [піт’ї́] ', ua: ' Напій', context: '',  association: '',},
  { id: 45, en: 'Snídaně [снї́данє] ', ua: ' Сніданок', context: '',  association: '',},
  { id: 46, en: 'Večeře [вєче́рже] ', ua: ' Вечеря', context: '',  association: '',},
  { id: 47, en: 'Dítě [дї́тє] ', ua: ' Дитина', context: '',  association: '',},
  { id: 48, en: 'Přítel [пржї́тєл] ', ua: ' Друг', context: '',  association: '',},
  { id: 49, en: 'Přítelkyně [пржї́тєлкінє] ', ua: ' Подруга', context: '',  association: '',},
  { id: 50, en: 'Rodiče [ро́дічє] ', ua: ' Батьки', context: '',  association: '',},
  { id: 51, en: 'Bratr [бра́тр] ', ua: ' Брат', context: '',  association: '',},
  { id: 52, en: 'Dcera [дце́ра] ', ua: ' Дочка', context: '',  association: '',},
  { id: 53, en: 'Krátký [кра́ткі] ', ua: ' Короткий', context: '',  association: '',},
  { id: 54, en: 'Šťastný [шчя́стни] ', ua: ' Щасливий', context: '',  association: '',},
  { id: 55, en: 'Smutný [сму́тни] ', ua: ' Сумний', context: '',  association: '',},
  { id: 56, en: 'Chudý [худі] ', ua: ' Бідний', context: '',  association: '',},
  { id: 57, en: 'Láska [ла́ска] ', ua: ' Любов', context: '',  association: '',},
  { id: 58, en: 'Štěstí [шчє́сті] ', ua: ' Щастя', context: '',  association: '',},
  { id: 59, en: 'Smrt [смерт] ', ua: ' Смерть', context: '',  association: '',},
  { id: 60, en: 'Život [жї́вот] ', ua: ' Життя', context: '',  association: '',},
  { id: 61, en: 'Přátelství [пржа́тєлстві] ', ua: ' Дружба', context: '',  association: '',},
  { id: 62, en: 'Nebe [не́бе] ', ua: ' Небо', context: '',  association: '',},
  { id: 63, en: 'Země [зє́мє] ', ua: ' Земля', context: '',  association: '',},
  { id: 64, en: 'Měsíc [мьєсі́ц] ', ua: ' Місяць', context: '',  association: '',},
  { id: 65, en: 'Hvězda [хвьє́зда] ', ua: ' Зірка', context: '',  association: '',},
  { id: 66, en: 'Oheň [о́гень] ', ua: ' Вогонь', context: '',  association: '',},
  { id: 67, en: 'Světlo [свьє́тло] ', ua: ' Світло', context: '',  association: '',},
  { id: 68, en: 'Dnes [днєс] ', ua: ' Сьогодні', context: '',  association: '',},
  { id: 69, en: 'Zítra [зї́тра] ', ua: ' Завтра', context: '',  association: '',},
  { id: 70, en: 'Včera [вчє́ра] ', ua: ' Вчора', context: '',  association: '',},
  { id: 71, en: 'Studený [студєни] ', ua: ' Холодний', context: '',  association: '',},
  { id: 72, en: 'Těžký [тєжки] ', ua: ' Важкий', context: '',  association: '',},
  { id: 73, en: 'Jasný [ясни] ', ua: ' Ясний', context: '',  association: '',},
  { id: 74, en: 'Oblaka [облака] ', ua: ' Хмари', context: '',  association: '',},
  { id: 75, en: 'Vichřice [вї́хріцє] ', ua: ' Вітер', context: '',  association: '',},
  { id: 76, en: 'Bouře [бо́уже] ', ua: ' Буря', context: '',  association: '',},
  { id: 77, en: 'Horko [горко] ', ua: ' Спека', context: '',  association: '',},
  { id: 78, en: 'Přítomnost [пржї́томност] ', ua: ' Сьогодення', context: '',  association: '',},
  { id: 79, en: 'Minulost [минулост] ', ua: ' Минуле', context: '',  association: '',},
  { id: 80, en: 'Budoucnost [будоуцност] ', ua: ' Майбутнє', context: '',  association: '',},
  { id: 81, en: 'Někdo [нєкдо] ', ua: ' Хтось', context: '',  association: '',},
  { id: 82, en: 'Nikdo [нікдо] ', ua: ' Ніхто', context: '',  association: '',},
  { id: 83, en: 'Něco [нєцо] ', ua: ' Щось', context: '',  association: '',},
  { id: 84, en: 'Jen [йєн] ', ua: ' Лише', context: '',  association: '',},
  { id: 85, en: 'Jako [я́ко] ', ua: ' Як', context: '',  association: '',},
  { id: 86, en: 'Protože [прото́же] ', ua: ' Тому що', context: '',  association: '',},
  { id: 87, en: 'Proč [про́ч] ', ua: ' Чому', context: '',  association: '',},
  { id: 88, en: 'Kdy [гди] ', ua: ' Коли', context: '',  association: '',},
  { id: 89, en: 'Odkud [одкуд] ', ua: ' Звідки', context: '',  association: '',},
  { id: 90, en: 'Kdyby [гдиби] ', ua: ' Якби', context: '',  association: '',},
  { id: 91, en: 'Před [пржєд] ', ua: ' Перед', context: '',  association: '',},
  { id: 92, en: 'Mezi [мєзі] ', ua: ' Між', context: '',  association: '',},
  { id: 93, en: 'Kromě [кроме] ', ua: ' Крім', context: '',  association: '',},
  { id: 94, en: 'Zaměstnání [замнє́стнани]', ua: 'Працевлаштування', context: '',  association: '',},
  { id: 95, en: 'Zaměstnanec [замнє́стнанєц]', ua: 'Працівник', context: '',  association: '',},
  { id: 96, en: 'Šéf [ше́ф]', ua: 'Начальник', context: '',  association: '',},
  { id: 97, en: 'Plat [плат]', ua: 'Зарплата', context: '',  association: '',},
  { id: 98, en: 'Kancelář [канцела́рш]', ua: 'Офіс', context: '',  association: '',},
  { id: 99, en: 'Schůzka [сху́зка]', ua: 'Зустріч', context: '',  association: '',},
  { id: 100, en: 'Tým [тїм]', ua: 'Команда', context: '',  association: '',},
  ];
