const dbEn = [
  {
    id: 1,
    en: 'yell',
    ua: 'кричати, волати, верещати',
    context:
      'In the midnight hour, she cried, More, more, moreWith a rebel yell, she cried, More, more, more, wow!',
    association: 'кричати, щоб аж ялинка тряслася',
  },
  {
    id: 2,
    en: 'widower',
    ua: 'вдівець',
    context: '',
    association: 'бачивший види вдівець',
  },
  {
    id: 3,
    en: 'in charge',
    ua: 'відповідальний',
    context: '',
    association: '',
  },
  { id: 4, en: 'split', ua: 'розкол', context: '', association: '' },
  { id: 5, en: 'chores', ua: 'клопоти', context: '', association: '' },
  {
    id: 6,
    en: 'get stuck',
    ua: 'застрягли',
    context: 'I am stuck',
    association: 'рука застрягла а стакані',
  },
  {
    id: 7,
    en: 'dot',
    ua: 'крапка',
    context: 'facebook dot com',
    association: 'дотиком пера робиться крапка',
  },
  { id: 8, en: 'squiggle', ua: 'карлючка', context: '', association: '' },
  {
    id: 9,
    en: 'interchangeably',
    ua: 'взаємозаміно',
    context: 'subclasses can be used interchangeably with their base class',
    association: '',
  },
  { id: 10, en: 'mold', ua: 'цвіль', context: '', association: '' },
  { id: 11, en: 'teensy', ua: 'крихітний', context: '', association: '' },
  { id: 12, en: 'fumes', ua: 'чад', context: '', association: '' },
  { id: 13, en: 'faucet', ua: 'кран', context: '', association: '' },
  { id: 14, en: 'suspicious', ua: 'підозрілий', context: '', association: '' },
  { id: 15, en: 'banish', ua: 'відганяти', context: '', association: '' },
  { id: 16, en: 'tap', ua: 'кран', context: '', association: '' },
  { id: 17, en: 'consequences', ua: 'наслідки', context: '', association: '' },
  {
    id: 18,
    en: 'environment',
    ua: 'навколишнє середовище',
    context: '',
    association: '',
  },
  {
    id: 19,
    en: 'underneath',
    ua: 'під',
    context:
      'Underneath the bridge downtown, is where I drew some blood, Underneath the bridge downtown, I could not get enough',
    association: 'під ним',
  },
  { id: 20, en: 'shanties', ua: 'халупки', context: '', association: '' },
  { id: 21, en: 'brat', ua: 'кодло', context: '', association: '' },
  { id: 22, en: 'precious', ua: 'дорогоцінний', context: '', association: '' },
  {
    id: 23,
    en: 'admit',
    ua: 'впустити, припустити, дозволити',
    context: 'Admittedly, this example is a bit contrived',
    association: 'адмін припускає дозвіл на встановлення ПЗ',
  },
  {
    id: 24,
    en: 'recall',
    ua: 'відгук, спогад',
    context: 'total recall',
    association: 'перевиклик',
  },
  { id: 25, en: 'nourished', ua: 'нагодовані', context: '', association: '' },
  { id: 26, en: 'harden', ua: 'укріпляти', context: '', association: '' },
  { id: 27, en: 'outcome', ua: 'результат', context: '', association: '' },
  {
    id: 28,
    en: 'reckless',
    ua: 'необачний, безрозсудний',
    context:
      'On and on, reckless abandonSomething`s wrong, this is gonna shock themNothing to hold on toWe`ll use this song to lead you on',
    association: 'рЕзиковий',
  },
  { id: 29, en: 'passionate', ua: 'пристрасний', context: '', association: '' },
  { id: 30, en: 'affair', ua: 'справа', context: '', association: '' },
  { id: 31, en: 'parcel', ua: 'посилка', context: '', association: '' },
  { id: 32, en: 'greed', ua: 'жадібність', context: '', association: '' },
  { id: 33, en: 'awful', ua: 'жахливий', context: '', association: '' },
  { id: 34, en: 'crap', ua: 'лайно', context: '', association: '' },
  { id: 35, en: 'pranks', ua: 'пустощі', context: '', association: '' },
  { id: 36, en: 'cogent', ua: 'переконливий', context: '', association: '' },
  { id: 37, en: 'abhorrent', ua: 'огидний', context: '', association: '' },
  { id: 38, en: 'racy', ua: 'колоритний', context: '', association: '' },
  { id: 39, en: 'sustain', ua: 'підтримувати', context: '', association: '' },
  { id: 40, en: 'trap-door', ua: 'люк', context: '', association: '' },
  { id: 41, en: 'parsley', ua: 'петрушка', context: '', association: '' },
  { id: 42, en: 'bloated', ua: 'роздутий', context: '', association: '' },
  { id: 43, en: 'scorn', ua: 'зневажати', context: '', association: '' },
  {
    id: 44,
    en: 'furious',
    ua: 'розлючений',
    context: 'fast and furious',
    association: 'розлючена фурія',
  },
  { id: 45, en: 'embracing', ua: 'охоплює', context: '', association: '' },
  {
    id: 46,
    en: 'assign',
    ua: 'призначати',
    context: 'variable assign',
    association: 'як знак',
  },
  {
    id: 47,
    en: 'mandatory',
    ua: 'обов`язковий',
    context: '',
    association: 'мандатний депутат, який обов`язковий для голосування',
  },
  { id: 48, en: 'arcana', ua: 'таємниці', context: '', association: '' },
  { id: 49, en: 'dormant', ua: 'бездіяльний', context: '', association: '' },
  {
    id: 50,
    en: 'offended',
    ua: 'ображатися',
    context: 'My tendency for dependency is offending me',
    association: 'без кінця ображатися',
  },
  {
    id: 51,
    en: 'ooze',
    ua: 'сочитися, болото, липкий бруд',
    context: 'abandoned barges sunk in ooze',
    association: 'вузька дірка, через яку витікає липкий бруд',
  },
  { id: 52, en: 'currently', ua: 'в даний час', context: '', association: '' },
  {
    id: 53,
    en: 'wreaking havoc',
    ua: 'мстилися',
    context: '',
    association: '',
  },
  { id: 54, en: 'dolts', ua: 'бовдури', context: '', association: '' },
  { id: 55, en: 'gnawing', ua: 'гризти', context: '', association: '' },
  { id: 56, en: 'broom', ua: 'мітла', context: '', association: '' },
  { id: 57, en: 'tether', ua: 'прив`язь', context: '', association: '' },
  { id: 58, en: 'civic', ua: 'цивільний', context: '', association: '' },
  {
    id: 59,
    en: 'regardless',
    ua: 'незважаючи на',
    context: '',
    association: '',
  },
  { id: 60, en: 'permission', ua: 'дозвіл', context: '', association: '' },
  { id: 61, en: 'regain', ua: 'повернути собі', context: '', association: '' },
  { id: 62, en: 'begat', ua: 'породив', context: '', association: '' },
  { id: 63, en: 'evolve', ua: 'еволюціонувати', context: '', association: '' },
  { id: 64, en: 'apparently', ua: 'мабуть', context: '', association: '' },
  { id: 65, en: 'fellow', ua: 'хлопець', context: '', association: '' },
  { id: 66, en: 'explore', ua: 'досліджувати', context: '', association: '' },
  { id: 67, en: 'mention', ua: 'згадати', context: '', association: '' },
  {
    id: 68,
    en: 'figure out',
    ua: 'здогадатися/уявити',
    context: '',
    association: '',
  },
  { id: 69, en: 'lousy', ua: 'паршивий', context: '', association: '' },
  { id: 70, en: 'debauchery', ua: 'розпуста', context: '', association: '' },
  {
    id: 71,
    en: 'besides',
    ua: 'крім того, додатково, також',
    context: '',
    association: 'бути на стороні також',
  },
  { id: 72, en: 'handsome', ua: 'красивий', context: '', association: '' },
  { id: 73, en: 'placated', ua: 'приборкати', context: '', association: '' },
  {
    id: 74,
    en: 'behold',
    ua: 'ось',
    context: 'Behold the flesh and the power it holds',
    association: 'будь тримаючим вісь (май стержня)',
  },
  {
    id: 75,
    en: 'tenure',
    ua: 'термін перебування',
    context: '',
    association: '',
  },
  {
    id: 76,
    en: 'certain wealthy',
    ua: 'певний багатим',
    context: '',
    association: '',
  },
  { id: 77, en: 'duct-taped', ua: 'скотчем', context: '', association: '' },
  { id: 78, en: 'evaluation', ua: 'оцінка', context: '', association: '' },
  { id: 79, en: 'stingy', ua: 'скупий', context: '', association: '' },
  {
    id: 80,
    en: 'kneeling',
    ua: 'стоячи на колінах',
    context: '',
    association: '',
  },
  {
    id: 81,
    en: 'pathetic',
    ua: 'патетичний, жалюгідний',
    context: 'you`re so pathetic',
    association: 'паяц жалюгідний',
  },
  {
    id: 82,
    en: 'affordable',
    ua: 'доступний, допустимий',
    context: '',
    association: 'а форд доступна машина',
  },
  { id: 83, en: 'delay', ua: 'затримка', context: '', association: '' },
  { id: 84, en: 'gravy', ua: 'підлива', context: '', association: '' },
  { id: 85, en: 'come through', ua: 'проникати', context: '', association: '' },
  { id: 86, en: 'defaced', ua: 'зіпсовані', context: '', association: '' },
  { id: 87, en: 'left out', ua: 'опущені', context: '', association: '' },
  { id: 88, en: 'advance', ua: 'просування', context: '', association: '' },
  { id: 89, en: 'preys', ua: 'полює', context: '', association: '' },
  { id: 90, en: 'convenient', ua: 'зручний', context: '', association: '' },
  {
    id: 91,
    en: 'self-sustaining',
    ua: 'самопідтримуючийся',
    context: '',
    association: '',
  },
  { id: 92, en: 'exist', ua: 'існувати', context: '', association: '' },
  {
    id: 93,
    en: 'all-consuming',
    ua: 'всепоглинаючої',
    context: '',
    association: '',
  },
  { id: 94, en: 'ignis', ua: 'оманлива надія', context: '', association: '' },
  {
    id: 95,
    en: 'humiliating',
    ua: 'принизливий',
    context: '',
    association: '',
  },
  { id: 96, en: 'chariot', ua: 'колісниця', context: '', association: '' },
  { id: 97, en: 'hick', ua: 'селюк', context: '', association: '' },
  { id: 98, en: 'bum', ua: 'дупа', context: '', association: '' },
  { id: 99, en: 'avoid', ua: 'уникнути', context: '', association: '' },
  { id: 100, en: 'lush', ua: 'пишний', context: '', association: '' },
  { id: 101, en: 'wrinkles', ua: 'зморшки', context: '', association: '' },
  {
    id: 102,
    en: 'retardant',
    ua: 'сповільнювач',
    context: '',
    association: '',
  },
  { id: 103, en: 'hideous', ua: 'огидний', context: '', association: '' },
  {
    id: 104,
    en: 'weird',
    ua: 'дивний',
    context: 'weird things will happen',
    association: '',
  },
  { id: 105, en: 'egregious', ua: 'кричущий', context: '', association: '' },
  { id: 106, en: 'gut', ua: 'потрошити', context: '', association: '' },
  { id: 107, en: 'tanning salon', ua: 'солярій', context: '', association: '' },
  { id: 108, en: 'testicle', ua: 'яєчко', context: '', association: '' },
  { id: 109, en: 'flare', ua: 'спалах', context: '', association: '' },
  { id: 110, en: 'bow down', ua: 'схилитися', context: '', association: '' },
  { id: 111, en: 'overlords', ua: 'королі', context: '', association: '' },
  { id: 112, en: 'score', ua: 'рахунок', context: '', association: '' },
  {
    id: 113,
    en: 'embarrassing',
    ua: 'скрутний, соромно',
    context: '',
    association: 'соромно емпатично трясти дупою в барі',
  },
  { id: 114, en: 'pit', ua: 'яма', context: '', association: '' },
  { id: 115, en: 'wristband', ua: 'браслет', context: '', association: '' },
  { id: 116, en: 'aisle', ua: 'приділ', context: '', association: '' },
  { id: 117, en: 'jealous', ua: 'ревнивий', context: '', association: '' },
  { id: 118, en: 'envious', ua: 'заздрісний', context: '', association: '' },
  {
    id: 119,
    en: 'bail on',
    ua: 'під заставу на',
    context: '',
    association: '',
  },
  { id: 120, en: 'generously', ua: 'щедро', context: '', association: '' },
  { id: 121, en: 'perform', ua: 'виконувати', context: '', association: '' },
  { id: 122, en: 'proper', ua: 'правильний', context: '', association: '' },
  {
    id: 123,
    en: 'parking lot',
    ua: 'стоянка для машин',
    context: '',
    association: '',
  },
  { id: 124, en: 'buck', ua: 'долар', context: '', association: '' },
  { id: 125, en: 'enthralling', ua: 'захоплює', context: '', association: '' },
  { id: 126, en: 'exclaim', ua: 'вигукувати', context: '', association: '' },
  {
    id: 127,
    en: 'stirring',
    ua: 'перемішування',
    context: '',
    association: '',
  },
  { id: 128, en: 'dump', ua: 'звалище', context: '', association: '' },
  { id: 129, en: 'cheapskate', ua: 'скнара', context: '', association: '' },
  {
    id: 130,
    en: 'corncob',
    ua: 'кукурудзяний качан',
    context: '',
    association: '',
  },
  {
    id: 131,
    en: 'restrict',
    ua: 'обмежувати',
    context: '',
    association: 'пере-більшити строгість',
  },
  { id: 132, en: 'prevalent', ua: 'превалюючий', context: '', association: '' },
  { id: 133, en: 'consider', ua: 'розглядати', context: '', association: '' },
  { id: 134, en: 'recent', ua: 'недавній', context: '', association: '' },
  {
    id: 135,
    en: 'being a pushover',
    ua: 'будучи слабовільний',
    context: '',
    association: '',
  },
  { id: 136, en: 'chimney', ua: 'димохід', context: '', association: '' },
  { id: 137, en: 'mistletoe', ua: 'омела біла', context: '', association: '' },
  { id: 138, en: 'generous', ua: 'щедрий', context: '', association: '' },
  { id: 139, en: 'snowflake', ua: 'сніжинка', context: '', association: '' },
  {
    id: 140,
    en: 'extended',
    ua: 'розширений',
    context: 'extended class',
    association: '',
  },
  { id: 141, en: 'Easter', ua: 'великодній', context: '', association: '' },
  { id: 142, en: 'brew', ua: 'заварювати', context: '', association: '' },
  { id: 143, en: 'scram', ua: 'котися', context: '', association: '' },
  {
    id: 144,
    en: 'load bearing wall',
    ua: 'несуча стіна',
    context: '',
    association: '',
  },
  { id: 145, en: 'assume', ua: 'вважати', context: '', association: '' },
  {
    id: 146,
    en: 'entertaining',
    ua: 'розважальний',
    context: '',
    association: '',
  },
  { id: 147, en: 'chirping', ua: 'стрекотіння', context: '', association: '' },
  {
    id: 148,
    en: 'slipped',
    ua: 'послизнувся',
    context:
      'callbacks are the functions that are slipped or passed into another function to decide the invocation of that function',
    association: 'сліпий слизький цуцик (тільки народився)',
  },
  {
    id: 149,
    en: 'underestimate',
    ua: 'недооцінювати',
    context:
      'Don`t underestimateYour heart is never lateAnd love will always find a way',
    association: 'підоцінка',
  },
  {
    id: 150,
    en: 'spot',
    ua: 'пляма',
    context: '',
    association: 'спітнів от і плями виступили',
  },
  { id: 151, en: 'pacifier', ua: 'заспокоювач', context: '', association: '' },
  { id: 152, en: 'insurance', ua: 'страхування', context: '', association: '' },
  { id: 153, en: 'revamp', ua: 'оновлюють', context: '', association: '' },
  { id: 154, en: 'bias', ua: 'зміщення', context: '', association: '' },
  { id: 155, en: 'conquest', ua: 'підкорення', context: '', association: '' },
  {
    id: 156,
    en: 'capacity',
    ua: 'ємність, місткість',
    context: '',
    association: '',
  },
  { id: 157, en: 'decent', ua: 'порядна', context: '', association: '' },
  { id: 158, en: 'reveal', ua: 'розкривати', context: '', association: '' },
  { id: 159, en: 'ominous', ua: 'загрозливий', context: '', association: '' },
  { id: 160, en: 'reassured', ua: 'заспокоїв', context: '', association: '' },
  { id: 161, en: 'creeping out', ua: 'вилазити', context: '', association: '' },
  {
    id: 162,
    en: 'descentdant',
    ua: 'спуск, нащадок, нижчій за ієрархією',
    context: 'descentdant compontnt',
    association: 'нащадок дисидента',
  },
  { id: 163, en: 'gibberish', ua: 'тарабарщина', context: '', association: '' },
  {
    id: 164,
    en: 'flooding',
    ua: 'затоплення',
    context: 'we are flooding in chat',
    association: 'флудити в чаті - додавати води в чисту інформацію',
  },
  { id: 165, en: 'rebates', ua: 'знижки', context: '', association: '' },
  { id: 166, en: 'gaze', ua: 'вдивлятися', context: '', association: '' },
  { id: 167, en: 'drool', ua: 'сочитися', context: '', association: '' },
  { id: 168, en: 'obviously', ua: 'очевидно', context: '', association: '' },
  {
    id: 169,
    en: 'consumption',
    ua: 'споживання',
    context: '',
    association: '',
  },
  { id: 170, en: 'baffling', ua: 'скрутний', context: '', association: '' },
  { id: 171, en: 'slobbering', ua: 'слинявий', context: '', association: '' },
  { id: 172, en: 'knot', ua: 'вузол', context: '', association: '' },
  { id: 173, en: 'belly', ua: 'живіт', context: '', association: '' },
  { id: 174, en: 'instantly', ua: 'негайно', context: '', association: '' },
  { id: 175, en: 'refills', ua: 'заправок', context: '', association: '' },
  {
    id: 176,
    en: 'conquering',
    ua: 'завойовуючи',
    context: '',
    association: '',
  },
  { id: 177, en: 'inedible', ua: 'неїстівний', context: '', association: '' },
  { id: 178, en: 'rooting', ua: 'вкорінення', context: '', association: '' },
  { id: 179, en: 'cubs', ua: 'дитинчата', context: '', association: '' },
  { id: 180, en: 'jolly', ua: 'веселий', context: '', association: '' },
  { id: 181, en: 'proper', ua: 'правильний', context: '', association: '' },
  { id: 182, en: 'stool', ua: 'стілець', context: '', association: '' },
  { id: 183, en: 'bounty', ua: 'щедрість', context: '', association: '' },
  {
    id: 184,
    en: 'pedegry',
    ua: 'історія життя, родословна',
    context: '',
    association: '',
  },
  {
    id: 185,
    en: 'infinity',
    ua: 'нескінченність',
    context: '∞',
    association: 'нескінченно дорога в обслуговуванні infinity',
  },
  {
    id: 186,
    en: 'inspire',
    ua: 'надихати',
    context: 'you inspire me to create this app',
    association: 'вдихнути життя всередину',
  },
  {
    id: 187,
    en: 'thrive',
    ua: 'процвітати',
    context: 'I just wanna thrive',
    association: 'потроюватися',
  },
  {
    id: 188,
    en: 'cloac',
    ua: 'плащ',
    context: 'Snapes cloac',
    association: 'клоака, щось потаємне',
  },
  {
    id: 189,
    en: 'mutter',
    ua: 'бурмотіти',
    context: 'Snapes muttering',
    association: 'мурчати',
  },
  {
    id: 190,
    en: 'token',
    ua: 'знак, сувенір',
    context: 'tokens from admires',
    association: 'то Кен а це Барбі (сувеніри)',
  },
  {
    id: 191,
    en: 'admire',
    ua: 'захоплюватися, милуватися',
    context: 'tokens from admires',
    association: 'адміралом всі захоплюються',
  },
  {
    id: 192,
    en: 'trunk',
    ua: 'багажник',
    context: 'jumping in my trunk',
    association: 'після транквілізатора людину пхають у багажник',
  },
  {
    id: 193,
    en: 'exception',
    ua: 'виняток',
    context: 'exept for the wine',
    association: '',
  },
  {
    id: 194,
    en: 'occur',
    ua: 'відбувається',
    context:
      'React expects you to never modify state directly, instead always use this.setState() when state changes occur.',
    association: 'окурок - значить тут відбувалися події',
  },
  {
    id: 195,
    en: 'malform',
    ua: 'неправильна форма',
    context: '',
    association: '',
  },
  { id: 196, en: 'ensure', ua: 'забезпечити', context: '', association: '' },
  { id: 197, en: 'gutter', ua: 'жолоб, канава', context: '', association: '' },
  {
    id: 198,
    en: 'hover',
    ua: 'наведення курсору',
    context: '',
    association: '',
  },
  { id: 199, en: 'indent', ua: 'відступ', context: '', association: '' },
  { id: 200, en: 'inset', ua: 'вставка', context: '', association: '' },
  {
    id: 201,
    en: 'reveal',
    ua: 'відкривати, виявляти',
    context: '',
    association: '',
  },
  {
    id: 202,
    en: 'breadcrumbs',
    ua: 'хлібні крихти',
    context: '',
    association: '',
  },
  {
    id: 203,
    en: 'scope',
    ua: 'сфера застосування',
    context: 'global/local/function scope',
    association: 'телескоп (обмежений)',
  },
  {
    id: 204,
    en: 'expand',
    ua: 'розширити',
    context: '',
    association: 'еспандер розширяє груди',
  },
  {
    id: 205,
    en: 'extension',
    ua: 'розширення',
    context: '',
    association: 'екстенсивний розвиток',
  },
  {
    id: 206,
    en: 'deprecate',
    ua: 'занепадати, застарівати',
    context: 'this approach is deprecated',
    association: 'те при Кате великій було - вже застаріло',
  },
  { id: 207, en: 'template', ua: 'шаблон', context: '', association: '' },
  { id: 208, en: 'inspiration', ua: 'натхнення', context: '', association: '' },
  { id: 209, en: 'gist', ua: 'суть', context: '', association: '' },
  { id: 210, en: 'wrap', ua: 'загорнути', context: '', association: '' },
  {
    id: 211,
    en: 'сondense',
    ua: 'ущільнювати',
    context: '',
    association: 'конденсатор ущільнює повітря',
  },
  {
    id: 212,
    en: 'inherit',
    ua: 'успадкувати',
    context:
      'Inheritance is an OOP feature where a class (child/subclass) inherits properties and methods from another class (parent/superclass), enabling code reuse and hierarchical relationships.',
    association: 'in her it (в ній це) - в мамі спадкоємець.',
  },
  {
    id: 213,
    en: 'grid',
    ua: 'сітка',
    context: 'display: grid',
    association: 'грати у в`язниці',
  },
  {
    id: 214,
    en: 'purchase',
    ua: 'покупка',
    context: 'skoda purchase',
    association: 'чиста погоня за накупами',
  },
  {
    id: 215,
    en: 'rush',
    ua: 'спішка',
    context: 'js rush course',
    association: 'руш/рушай - поспішай',
  },
  {
    id: 216,
    en: 'request',
    ua: 'запит',
    context: 'pull request',
    association: 'запит на повторене проходження квесту',
  },
  {
    id: 217,
    en: 'fetch',
    ua: 'принести, привести',
    context: 'A doctor was not fetched by the nurse.',
    association:
      'to go to a place to get something or someone and bring them back',
  },
  {
    id: 218,
    en: 'curious',
    ua: 'допитливий, цікавий',
    context: 'curious, i have never seen birds like this',
    association: 'курйоз (пізнавально)',
  },
  {
    id: 219,
    en: 'invocation',
    ua: 'звернення',
    context: 'invocation to variable',
    association: 'інвойс (рахунок з яким до мене звертаються)',
  },
  {
    id: 220,
    en: 'transparent',
    ua: 'прозорий',
    context: 'background-color: transparent',
    association: 'транспарант на якому нічого немає',
  },
  {
    id: 221,
    en: 'hustle',
    ua: 'суєта',
    context: 'You do not need side hustle',
    association: 'гасити пожежу (суєтливо)',
  },
  {
    id: 222,
    en: 'execute',
    ua: 'виконувати',
    context: 'code executions',
    association: 'exe - запуск, робота додатку',
  },
  {
    id: 223,
    en: 'assign',
    ua: 'назначати',
    context: 'assign the number to variable',
    association: 'as sign - як знак, на знак',
  },
  {
    id: 224,
    en: 'statement',
    ua: 'інструкція',
    context: 'statement expected',
    association: 'обґрунтування',
  },
  {
    id: 225,
    en: 'expression-statement',
    ua: 'вираз-інструкція',
    context: '',
    association: '',
  },
  {
    id: 226,
    en: 'occurrence',
    ua: 'випадок, виникнення',
    context: 'change all occurrences',
    association: 'акуратно - передбачуючи всі випадки.',
  },
  {
    id: 227,
    en: 'instanceof',
    ua: 'екземпляр',
    context: 'instanceof class',
    association: 'інстанція бюрократії',
  },
  {
    id: 228,
    en: 'resolve',
    ua: 'вирішити',
    context: 'resolve, solve',
    association: '',
  },
  {
    id: 229,
    en: 'pending',
    ua: 'висячий, невирішений',
    context: 'pending reqest',
    association: 'просячий пендаля чарівного',
  },
  {
    id: 230,
    en: 'revert',
    ua: 'повернутися до якоїсь справи',
    context: 'revert to section 2',
    association: 'пере-вернутися',
  },
  {
    id: 231,
    en: 'pagination',
    ua: 'нумерування рядків',
    context: 'spread array of information to pages',
    association: 'розкладання на pages',
  },
  {
    id: 232,
    en: 'bunch of',
    ua: 'купа',
    context: 'bunch of isolatet comonents',
    association: 'купа каміння в бані',
  },
  {
    id: 233,
    en: 'dash',
    ua: 'тире',
    context: 'node --v',
    association: 'low dash _ library',
  },
  {
    id: 234,
    en: 'essentially',
    ua: 'по суті',
    context: 'React is essentialy a tree of components',
    association: 'есенція',
  },
  {
    id: 235,
    en: 'implementation',
    ua: 'впровадження',
    context: 'implementation of logic to our code',
    association: 'імплементація ранкової зарядки',
  },
  {
    id: 236,
    en: 'spread',
    ua: 'розповсюдження',
    context: 'spread object',
    association: 'спрей - розпилювач',
  },
  {
    id: 237,
    en: 'bind',
    ua: 'зв`язати',
    context: '',
    association: 'біндер, бинт для перев`язки',
  },
  {
    id: 238,
    en: 'append',
    ua: 'додавати',
    context: '.append(button.render())',
    association: 'апендикс (додатковий орган)',
  },
  {
    id: 239,
    en: 'toggle',
    ua: 'перемикач',
    context: 'toggled automatically',
    association: 'вибір того положення',
  },
  {
    id: 240,
    en: 'alias',
    ua: 'псевдонім',
    context: 'alias of function',
    association: 'Alice - who the fucking Alice?',
  },
  {
    id: 241,
    en: 'intersect',
    ua: 'перетинатись',
    context: 'isIntersection: true',
    association: 'вхід в секцію (іншого об`єкту)',
  },
  {
    id: 242,
    en: 'invoke',
    ua: 'викликати',
    context: 'invoked listener',
    association: 'in wake - в підйомі. інвок - викликати, евок - евакуювати',
  },
  {
    id: 243,
    en: 'bundles',
    ua: 'об`єднувати, зв`язувати',
    context: 'Bundles the app into static files for production.',
    association: 'бандаж',
  },
  {
    id: 244,
    en: 'vital',
    ua: 'життево важливий',
    context: '',
    association: '',
  },
  {
    id: 245,
    en: 'curly braces',
    ua: '{}',
    context: 'when we insert dynamic value - we use curly brackets',
    association: 'скривлені (curved)',
  },
  {
    id: 246,
    en: 'square braces',
    ua: '[]',
    context: 'to get the key we can call it in expression in square brackets',
    association: 'square',
  },
  {
    id: 247,
    en: 'parentheses',
    ua: '()',
    context: 'add a parentheses',
    association:
      'додають дужкам властивостей батьків, так як підвищують пріоритет виконання операцій',
  },
  { id: 248, en: 'semicolon', ua: ';', context: ';', association: '' },
  { id: 249, en: 'comma', ua: ',', context: ',', association: '' },
  { id: 250, en: 'quotes', ua: '', context: '', association: '' },
  {
    id: 251,
    en: 'suspend',
    ua: 'призупинити',
    context: 'suspend the selected component',
    association: 'сюсюмусю… (ні те ні се)',
  },
  {
    id: 252,
    en: 'further',
    ua: 'далі, потім',
    context: 'variable for further inspection',
    association: 'фюрер',
  },
  {
    id: 253,
    en: 'external',
    ua: 'зовнішній',
    context: 'external component',
    association:
      'екстерном здають екзамени тільки зовнішні студенти, які не ходили на лекції',
  },
  {
    id: 254,
    en: 'nest',
    ua: 'вкладати',
    context: 'nest component',
    association: 'внести',
  },
  {
    id: 255,
    en: 'deploy',
    ua: 'розгортати',
    context: 'deploy component',
    association: 'плойка - закручує волосся, а деплойка розгортає.',
  },
  {
    id: 256,
    en: 'grasp',
    ua: 'швидко сприймати',
    context: 'grasp the concept',
    association: 'заходить як гра',
  },
  {
    id: 257,
    en: 'layout',
    ua: 'макет',
    context: 'layout of page',
    association: '',
  },
  {
    id: 258,
    en: 'deviate',
    ua: 'відхилятися',
    context: 'deviate from regular HTML atribute name',
    association: 'девіантна поведінка (відхилення від норми)',
  },
  {
    id: 259,
    en: 'validation',
    ua: 'перевірка, затвердження',
    context: 'browser validation',
    association: 'валід (гідний) - інвалід (не гідний)',
  },
  {
    id: 260,
    en: 'attend',
    ua: 'відвідувати',
    context: 'attend Firebase Summit',
    association: 'attention - увага, attend - уважити (своєю присутністю)',
  },
  {
    id: 261,
    en: 'engage',
    ua: 'залучати',
    context: 'engage friends',
    association: 'gage - виклик на двобій',
  },
  {
    id: 262,
    en: 'subscribe',
    ua: 'підписатися',
    context: 'subscribe to the Firebase Channel',
    association: 'scribe - писар, який шкребе пером',
  },
  {
    id: 263,
    en: 'evaluate',
    ua: 'оцінити',
    context: 're evaluate the code',
    association: 'оцінити еволюцію прогресу',
  },
  {
    id: 264,
    en: 'prior',
    ua: 'попередній',
    context: 'prior React knowledge',
    association: 'пріоритети - попередні умови',
  },
  {
    id: 265,
    en: 'everything by scratch',
    ua: 'з нуля',
    context: '',
    association: '',
  },
  {
    id: 266,
    en: 'prerequisite',
    ua: 'передумова',
    context: '',
    association: 'пререківзити…',
  },
  {
    id: 267,
    en: 'dismiss',
    ua: 'відхиляти, вигнати',
    context: 'click anywhere to dismiss the toast',
    association: 'не сумувати за тим що позбувся',
  },
  {
    id: 268,
    en: 'similar',
    ua: 'подібне',
    context: 'similar pages',
    association: 'такі самі',
  },
  {
    id: 269,
    en: 'implicitly',
    ua: 'неявно',
    context: 'function implicitly',
    association: 'як імплантат',
  },
  {
    id: 270,
    en: 'obviously',
    ua: 'явно',
    context: 'obviously function',
    association: 'оба видять ока',
  },
  {
    id: 271,
    en: 'suggestion',
    ua: 'пропозиція, натяк, порада',
    context: 'suggestion we need to configure',
    association: 'шагнути (з пропозицією)',
  },
  {
    id: 272,
    en: 'credential',
    ua: 'облікові дані',
    context: 'user credentials',
    association: 'кредитні карти з обліковими даними',
  },
  {
    id: 273,
    en: 'initialize',
    ua: 'ініціалізувати',
    context: 'initialize variable',
    association: '',
  },
  {
    id: 274,
    en: 'precise',
    ua: 'точний, чіткий',
    context:
      'PremeditatedCalculated, preciseCreated cases based on racesExchanging life for lies, exchanging life for lies',
    association: 'пре сайз - примірили розмір',
  },
  {
    id: 275,
    en: 'transition',
    ua: 'перехід',
    context: 'transition ease-in-out',
    association: 'транзит',
  },
  {
    id: 276,
    en: 'overwise',
    ua: 'премудрий',
    context: '',
    association: 'над мудрий',
  },
  {
    id: 277,
    en: 'otherwise',
    ua: 'інакший',
    context: 'we do it otherwise we do that',
    association: 'інша мудрість',
  },
  {
    id: 278,
    en: 'dummy',
    ua: 'не робочий, підставний',
    context: 'dummy data',
    association: '',
  },
  {
    id: 279,
    en: 'relate',
    ua: 'стосуватися, стосується',
    context: 'related to this subject',
    association: 'пов`язане',
  },
  {
    id: 280,
    en: 'specified',
    ua: 'вказано, уточнено',
    context: 'the specified value',
    association: 'специфіковано',
  },
  {
    id: 281,
    en: 'plenty',
    ua: 'багато',
    context: 'plenty spinners',
    association: '',
  },
  {
    id: 282,
    en: 'particular',
    ua: 'зокрема, окремо, особливий',
    context: 'we look at this particular',
    association: 'часнинно',
  },
  {
    id: 283,
    en: 'furnish',
    ua: 'обстановка, меблювання',
    context: 'furnished house',
    association: 'фурнітура',
  },
  {
    id: 284,
    en: 'latitude',
    ua: 'широта',
    context: '',
    association: 'наскільки латентна',
  },
  {
    id: 285,
    en: 'longtitude',
    ua: 'довгота',
    context: '',
    association: 'наскільки довго',
  },
  {
    id: 286,
    en: 'clue',
    ua: 'підказка, ключ',
    context: 'I don`t have any clue',
    association: 'ключ',
  },
  {
    id: 287,
    en: 'loop through',
    ua: 'пройтися (по переліку)',
    context: 'loop through the list',
    association: 'лупати очима на перелік покупок',
  },
  {
    id: 288,
    en: 'weird',
    ua: 'дивно',
    context: 'looling weird',
    association: 'вердикт - ти дивний і все!',
  },
  {
    id: 289,
    en: 'truncate',
    ua: 'урізати',
    context: 'truncate the text',
    association: 'труна, траншея',
  },
  {
    id: 290,
    en: 'trial',
    ua: 'пробний, випробування',
    context: 'I am ready for my trial',
    association: 'спроба - try',
  },
  {
    id: 291,
    en: 'swipe',
    ua: 'провести пальцем',
    context: 'swiper',
    association: '',
  },
  {
    id: 292,
    en: 'appropriate',
    ua: 'відповідний, належний',
    context: 'provide an appropriate age between 0 and 99',
    association: 'а про приятеля (відповідного, ну того, кого ти знаєш)',
  },
  {
    id: 293,
    en: 'brace',
    ua: 'фігурна дужка, клярма, скоба',
    context: '{}',
    association: 'як пловець, пливе брасом - вид зверху {',
  },
  {
    id: 294,
    en: 'pale',
    ua: 'блідий, слабкий, межа, огорожа',
    context: 'Is something wrong?You`re looking kind of pale',
    association: 'спалився і побілів',
  },
  {
    id: 295,
    en: 'omit',
    ua: 'пропускати, оминати',
    context: 'this parameter may be ommited',
    association: 'оминати',
  },
  {
    id: 296,
    en: 'plural',
    ua: 'множина',
    context: 'docs is plural',
    association: 'плюралізм думок',
  },
  {
    id: 297,
    en: 'entire',
    ua: 'цілий, повний',
    context: 'intired home component',
    association: 'повний інтерес',
  },
  {
    id: 298,
    en: 'stubborn',
    ua: 'впертий, завзятий',
    context: '',
    association: 'стабільно народжений',
  },
  {
    id: 299,
    en: 'whether',
    ua: 'чи, або',
    context: '',
    association: 'візир, звертаюся, коли в мене є питання або або',
  },
  {
    id: 300,
    en: 'propagation',
    ua: 'поширення',
    context: '',
    association: 'пропаганда',
  },
  {
    id: 301,
    en: 'outermost',
    ua: 'зовнішній',
    context: '',
    association: 'зовнішній мост',
  },
  {
    id: 302,
    en: 'clumsy',
    ua: 'незграбний',
    context: '',
    association: 'клешні а не руки - все падає',
  },
  {
    id: 303,
    en: 'decent',
    ua: 'пристойний',
    context: '',
    association: 'пристойний дисидент',
  },
  {
    id: 304,
    en: 'hoisting',
    ua: 'підйомний',
    context: '',
    association: 'гойдаючий підйомний механізм',
  },
  {
    id: 305,
    en: 'interruption',
    ua: 'переривання',
    context: '',
    association: 'введення рубки (вирубання)',
  },
  {
    id: 306,
    en: 'intended',
    ua: 'призначений',
    context: '',
    association: 'nintendo призначене для мене',
  },
  {
    id: 307,
    en: 'embrace',
    ua: 'обійняти',
    context: 'let me embrace you like a friend',
    association: 'закрити в дужки',
  },
  {
    id: 308,
    en: 'word of mouth',
    ua: 'сарафанне радіо (передача інформації з вуст в уста)',
    context: '',
    association: '',
  },
  { id: 309, en: 'nudity', ua: 'нагота', context: '', association: '' },
  { id: 310, en: 'humiliate', ua: 'принижувати', context: '', association: '' },
  {
    id: 311,
    en: 'glisten',
    ua: 'блищати, сяяти',
    context: '',
    association: '',
  },
  {
    id: 312,
    en: 'crump',
    ua: 'гуркіт, глухий удар',
    context: '',
    association: '',
  },
  {
    id: 313,
    en: 'take a bow',
    ua: 'поклонитися',
    context: '',
    association: '',
  },
  {
    id: 314,
    en: 'toss',
    ua: 'підкинути',
    context: 'toss me a pen',
    association: 'like pass',
  },
  {
    id: 315,
    en: 'odd',
    ua: 'дивний, випадковий, непарний',
    context: '',
    association: 'одурений, одинокий',
  },
  {
    id: 316,
    en: 'procreate',
    ua: 'продовжувати рід',
    context: '',
    association: 'продовжувати створення собі подібних',
  },
  {
    id: 317,
    en: 'terrain',
    ua: 'рельєф місцевості',
    context: 'familiar terrain',
    association: 'терикони',
  },
  {
    id: 318,
    en: 'cusp',
    ua: 'пік',
    context: 'I am on the cusp',
    association: 'каспер був завжди нагорі, тому що привід міг літати високо',
  },
  { id: 319, en: 'attain', ua: 'досягти', context: '', association: '' },
  {
    id: 320,
    en: 'flip',
    ua: 'сальто',
    context: 'back flip',
    association: 'back flip - чювак, єта репчик',
  },
  {
    id: 321,
    en: 'stake',
    ua: 'ставка',
    context: 'lives are at stake',
    association: '',
  },
  {
    id: 322,
    en: 'preserve',
    ua: 'зберегти',
    context: 'preserve its memory',
    association: 'законсервувати',
  },
  {
    id: 323,
    en: 'schlock',
    ua: 'шлак, барахло, халтура',
    context: 'you kept writing schlock',
    association: 'шлак',
  },
  {
    id: 324,
    en: 'sinkhole',
    ua: 'воронка',
    context: '',
    association: 'тонуча діра',
  },
  {
    id: 325,
    en: 'do you mind',
    ua: 'ви не проти?',
    context: '',
    association: 'ти думаєш про себе щось',
  },
  {
    id: 326,
    en: 'grudge',
    ua: 'образа',
    context: 'grudge against you',
    association: 'град без р (гад)',
  },
  {
    id: 327,
    en: 'perish',
    ua: 'здохнути',
    context: 'perish like a dog',
    association: 'померти з перцем (жалюгідно)',
  },
  {
    id: 328,
    en: 'vapid',
    ua: 'пустий, вульгарний не смачний',
    context: '',
    association: '',
  },
  {
    id: 329,
    en: 'nap',
    ua: 'короткий сон удень',
    context: 'try to take a nap',
    association: 'напоспати',
  },
  {
    id: 330,
    en: 'vain',
    ua: 'марно',
    context: 'in vain',
    association: 'брюс вейн марно сперечався з джокером',
  },
  {
    id: 331,
    en: 'courtship',
    ua: 'залицяння',
    context: 'it was a courtship',
    association: 'перед тим як піти до суду для одруження',
  },
  { id: 332, en: 'buffalo', ua: 'буйвол, бізон', context: '', association: '' },
  {
    id: 333,
    en: 'grunt',
    ua: 'бурчання, рохкання',
    context: '',
    association: 'gRRRRunt',
  },
  {
    id: 334,
    en: 'frighten',
    ua: 'лякати',
    context: 'I did not ftighten it',
    association: '',
  },
  {
    id: 335,
    en: 'pant',
    ua: 'палко дихати (задихатися)',
    context: 'panting',
    association: 'пантуватися (бігти, щоб аж задишка була)',
  },
  {
    id: 336,
    en: 'flood',
    ua: 'злива, повінь, потоп, вплив',
    context: 'where was a flood that year',
    association: 'флудити в чаті - додавати води в чисту інформацію',
  },
  {
    id: 337,
    en: 'onward',
    ua: 'уперед, наперед',
    context: 'onward, brother',
    association: 'на перед',
  },
  {
    id: 338,
    en: 'fetter',
    ua: 'окови, пута',
    context: 'fattered by my queen',
    association: 'светр, який сковує рухи',
  },
  {
    id: 339,
    en: 'bound',
    ua: 'зв`язаний',
    context: 'we are ever bound',
    association: 'бандаж',
  },
  {
    id: 340,
    en: 'parsley',
    ua: 'петрушка',
    context: '',
    association: 'петрушка з носу Елвіса Преслі стирчіть',
  },
  {
    id: 341,
    en: 'bumblebee',
    ua: 'джміль',
    context: '',
    association: 'джміль вдарився об бампер',
  },
  {
    id: 342,
    en: 'venom',
    ua: 'отрута',
    context: '',
    association: 'тече по венах',
  },
  { id: 343, en: 'hernia', ua: 'грижа', context: '', association: 'херня' },
  {
    id: 344,
    en: 'vinegar',
    ua: 'оцет',
    context: '',
    association: 'виноград залитий оцетом',
  },
  {
    id: 345,
    en: 'marsh',
    ua: 'болото',
    context: '',
    association: 'марширують солдати в болоті',
  },
  {
    id: 346,
    en: 'disguise',
    ua: 'маскування',
    context: 'You`re puttin` on a wonderful disguise',
    association: 'ці хлопці - я від них ховаюся (маскуюся)',
  },
  {
    id: 347,
    en: 'irritate',
    ua: 'дратувати',
    context: 'little irritated',
    association: 'коли немає Іри довго',
  },
  {
    id: 348,
    en: 'anxious',
    ua: 'тривожний, занепокоїний',
    context: '',
    association: 'анексією Криму була занепокоєна Європа',
  },
  {
    id: 349,
    en: 'reassuringly',
    ua: 'заспокійливо',
    context: '',
    association: 'завіряючи',
  },
  {
    id: 350,
    en: 'flirtatiously',
    ua: 'кокетливе',
    context: '',
    association: 'фліртуючи',
  },
  {
    id: 351,
    en: 'dismissively',
    ua: 'зневажливо',
    context: '',
    association: 'відхиляючись (dismiss)',
  },
  {
    id: 352,
    en: 'narrow',
    ua: 'вузький',
    context: 'narrow tube',
    association: 'нора (вузька)',
  },
  {
    id: 353,
    en: 'buckwheat',
    ua: 'гречка',
    context: '',
    association: 'як бісквіт',
  },
  {
    id: 354,
    en: 'fret',
    ua: 'нервувати',
    context: 'fret not',
    association: 'нервуватись фретно',
  },
  {
    id: 355,
    en: 'crucian',
    ua: 'карась',
    context: '',
    association: 'крушіан (круши кацапів)',
  },
  {
    id: 356,
    en: 'polite',
    ua: 'ввічливий',
    context: 'be polite',
    association: 'ввічливий Іполит',
  },
  {
    id: 357,
    en: 'gap',
    ua: 'розрив, діра, пробоїна, пробіл',
    context: '',
    association: 'гепнув так, що діру пробив',
  },
  {
    id: 358,
    en: 'rather',
    ua: 'скоріше за все, вірніше',
    context: 'use this option rather',
    association: 'рафік швидкої допомоги',
  },
  {
    id: 359,
    en: 'impact',
    ua: 'вплив, закріпляти',
    context: 'make it again for impact',
    association: 'закріпити імперським актом',
  },
  {
    id: 360,
    en: 'quiz',
    ua: 'вікторина, дивна річ, насмішка',
    context: 'challenges in sololearn are a kind of quiz of 5 questions ',
    association:
      'дивна річ: квизяючий хлопчик, з якого насміхаються, що він не виграв вікторину',
  },
  {
    id: 361,
    en: 'distinct',
    ua: 'виразний, відмінний, не схожий',
    context: 'TS has a distinct OOP style',
    association: 'не схожий на інстинкт',
  },
  {
    id: 362,
    en: 'shorthand',
    ua: 'скорочення',
    context: '',
    association: 'скорочена робота для рук',
  },
  {
    id: 363,
    en: 'swap',
    ua: 'обмін, міняти',
    context: 'swap the values of a and b',
    association: 'заміна з воплями',
  },
  {
    id: 364,
    en: 'patience',
    ua: 'терпіння, витримка',
    context: '',
    association: 'пацієнт, терплячий біль',
  },
  {
    id: 365,
    en: 'shallow',
    ua: 'не глибокий, мілководний',
    context: '',
    association: 'шаланди повні мілководної риби до Одеси Костя привозив',
  },
  {
    id: 366,
    en: 'certain',
    ua: 'певний, відомий, безсумнівний',
    context: 'certain мфдгу',
    association: 'певний сьогун',
  },
  {
    id: 367,
    en: 'borrow',
    ua: 'позичати, боргувати',
    context: '',
    association: 'борг',
  },
  {
    id: 368,
    en: 'obtain',
    ua: 'отримати, бути визнаним',
    context: 'iterator is used to obtain the values to be iterated',
    association: 'Обштейн був визнаним і отримав нобелівську премію',
  },
  {
    id: 369,
    en: 'adjustment',
    ua: 'коригування, регулювання',
    context: 'component ajustments',
    association: 'атрегулювати',
  },
  {
    id: 370,
    en: 'tremendouslyly',
    ua: 'надзвичайно',
    context: '',
    association: 'тремтить ДОС від надзвичайного морозу',
  },
  {
    id: 371,
    en: 'asset',
    ua: 'актив, цінність',
    context: '',
    association: 'цінна касета',
  },
  {
    id: 372,
    en: 'chunk',
    ua: 'шматок, частина',
    context: '',
    association: 'ЧАстиНКа',
  },
  {
    id: 373,
    en: 'breakdown',
    ua: 'зламатися, розподілитися',
    context: 'breakdown responsibilities',
    association: 'зламати і покласти (розкласти)',
  },
  {
    id: 374,
    en: 'retrive',
    ua: 'отримати, повернути собі, відновити',
    context: 'we just used to retrieve the last character in a string',
    association: 'переотримати',
  },
  {
    id: 375,
    en: 'afford',
    ua: 'дозволити собі, мати змогу',
    context: '',
    association: 'а форд я можу собі дозволити?',
  },
  {
    id: 376,
    en: 'distinguish',
    ua: 'розрізняти, відокремлювати, характеризувати',
    context: 'computers distinguish between numbers',
    association: 'діагностичне розрізнення',
  },
  {
    id: 377,
    en: 'respectively',
    ua: 'відповідно',
    context: '',
    association: 'респект відповідно до кожного',
  },
  {
    id: 378,
    en: 'sake',
    ua: 'користь, заради',
    context: 'sake of clarity',
    association: 'корисний годинник сейко',
  },
  {
    id: 379,
    en: 'subsequent',
    ua: 'наступний, що є результатом',
    context: 'each subsequent word is capitalized',
    association: 'підсиквел, наступна серія',
  },
  {
    id: 380,
    en: 'due',
    ua: 'через, належний',
    context: 'an error due to reassigning',
    association: 'належний дюк',
  },
  {
    id: 381,
    en: 'subtract',
    ua: 'віднімати',
    context: 'symbol for subtraction (-)',
    association: 'субстрат от цілого',
  },
  {
    id: 382,
    en: 'precision',
    ua: 'точність',
    context: 'they are computed with finite precision',
    association: 'точно точений прес',
  },
  {
    id: 383,
    en: 'explicit',
    ua: 'явний, однозначний',
    context: 'assign an explicit key to list items',
    association: '',
  },
  {
    id: 384,
    en: 'provide',
    ua: 'забезпечити, надати',
    context: '',
    association: 'провайдер надає інтернет',
  },
  {
    id: 385,
    en: 'typo',
    ua: 'одрук',
    context: '',
    association: 'типу помилився…',
  },
  { id: 386, en: 'axis', ua: 'вісь', context: '', association: '' },
  {
    id: 387,
    en: 'via',
    ua: 'через, за допомогою',
    context: 'way to append data to the end of an array is via the push()',
    association: 'віагра потрапила на сцену через постіль',
  },
  {
    id: 388,
    en: 'ancestor',
    ua: 'предок',
    context: '',
    association: 'аркестр предків',
  },
  {
    id: 389,
    en: 'precedence',
    ua: 'пріоритет',
    context: 'the local variable takes precedence over the global variable',
    association: 'президент має пріоритет',
  },
  {
    id: 390,
    en: 'leap',
    ua: 'стрибок, різка зміна, перешкода',
    context: '',
    association: 'відлип і стрибнув через перешкоду',
  },
  {
    id: 391,
    en: 'concern',
    ua: 'заклопотаність, важливість, занепокоєння, концерн',
    context: '',
    association: '',
  },
  {
    id: 392,
    en: 'obvious',
    ua: 'очевидний, зрозумілий, відкритий, банальний',
    context: '',
    association: 'обвів поглядом і все зрозумів',
  },
  {
    id: 393,
    en: 'fed up',
    ua: 'набридло',
    context: '',
    association: 'набридливий федя',
  },
  {
    id: 394,
    en: 'eventually',
    ua: 'з рештою, за певних обставин, в кінцевому рахунку',
    context: '',
    association: 'якщо стався якийсь івент',
  },
  {
    id: 395,
    en: 'solely',
    ua: 'виключно, єдино, самостійно',
    context: 'solely in this case',
    association: 'виключна соленина',
  },
  {
    id: 396,
    en: 'queue',
    ua: 'черга',
    context:
      'queue is an abstract Data Structure where items are kept in order',
    association: 'черга в КІОск',
  },
  {
    id: 397,
    en: 'denote',
    ua: 'позначити, виражати вказувати',
    context: '',
    association: 'занотувати',
  },
  {
    id: 398,
    en: 'pat',
    ua: 'погладити',
    context: 'pat your back',
    association: 'гладь свою домашню тварину',
  },
  {
    id: 399,
    en: 'mockup',
    ua: 'макет, підробка, знущання',
    context: 'she mocks me - I`m not fighter',
    association:
      'мокаючи перо створюється макет, мокають носом у нечистоти - знущаються',
  },
  {
    id: 400,
    en: 'redundant',
    ua: 'надлишковий, багатий, розтягнутий, зайвий',
    context: '',
    association: 'редуценти переробляють надлишкові органічні речовини',
  },
  {
    id: 401,
    en: 'skew',
    ua: 'перекіс, асиметричний, косий, перекошений',
    context: '',
    association: 'скюкожений',
  },
  {
    id: 402,
    en: 'span',
    ua: 'проліт, інтервал',
    context: '',
    association: 'з пана в князі через інтервал',
  },
  {
    id: 403,
    en: 'increment',
    ua: 'приріст, збільшення, прибуток',
    context: '',
    association: 'інкрментуємо збільшення',
  },
  {
    id: 404,
    en: 'embed',
    ua: 'вбудувати, вправляти',
    context: '',
    association: 'вбудоване в землю місто ембер',
  },
  {
    id: 405,
    en: 'disposal',
    ua: 'утилізація, диспозиція, вручення',
    context: '',
    association: 'диспозиція',
  },
  {
    id: 406,
    en: 'irrespective',
    ua: 'незалежно, безвідносно',
    context: '',
    association: 'незПОважаючи',
  },
  {
    id: 407,
    en: 'tile',
    ua: 'черепичний, плитка, кахель',
    context: '',
    association: 'стильна плитка',
  },
  {
    id: 408,
    en: 'maintain',
    ua: 'підтримувати, утримувати, втримувати',
    context: '',
    association: 'маніпені підтримувала Бонда',
  },
  {
    id: 409,
    en: 'aspect',
    ua: 'аспект, бік, вигляд',
    context: '',
    association: 'аспект (сторона)',
  },
  {
    id: 410,
    en: 'ratio',
    ua: 'співвідношення, пропорція',
    context: '',
    association: 'співвідношення раціону харчування',
  },
  {
    id: 411,
    en: 'appalling',
    ua: 'жахливий, страхітливий',
    context: '',
    association: 'наполі битви було жахливо',
  },
  {
    id: 412,
    en: 'divorce',
    ua: 'розлучення, розрив',
    context: '',
    association: 'розлучення з ворсистим партнером',
  },
  {
    id: 413,
    en: 'subtle',
    ua: 'гострий, тонкий, витончений',
    context: '',
    association: 'тонке сідло',
  },
  {
    id: 414,
    en: 'decelerate',
    ua: 'уповільнювати',
    context: '',
    association: 'децельна швидкість',
  },
  {
    id: 415,
    en: 'abrupt',
    ua: 'різкий, грубий, різкий',
    context: '',
    association: 'обрубаний',
  },
  {
    id: 416,
    en: 'mutual',
    ua: 'взаємний',
    context: '',
    association: 'взаємно мутуючій',
  },
  {
    id: 417,
    en: 'counterpart',
    ua: 'двійник, дублікат, копія',
    context: '',
    association: 'порахована частина',
  },
  {
    id: 418,
    en: 'encounter',
    ua: 'зустріч, сутичка, дуель',
    context: '',
    association: 'сутичка в дискаунтері',
  },
  {
    id: 419,
    en: 'enhance',
    ua: 'покращувати, збільшувати',
    context: '',
    association:
      'щоб співати в Hansons треба постійно покращувати свої музичні навички',
  },
  {
    id: 420,
    en: 'intention',
    ua: 'намір',
    context: 'Use as explanation of intent',
    association: 'інтенсивний намір',
  },
  {
    id: 421,
    en: 'arbitrary',
    ua: 'довільний, примхливий',
    context: 'They allow for arbitrary combinations',
    association: 'примхливий арбітр',
  },
  {
    id: 422,
    en: 'draw(er)',
    ua: 'тягнути (шухляда)',
    context: 'draws in - втягуватись',
    association: 'драйвер столу',
  },
  {
    id: 423,
    en: 'persist',
    ua: 'зберігаються, наполягати, залишаються',
    context: 'useRef Hook allows you to persist values between renders.',
    association: 'персики зберігаються довго, якщо залишаються в холодильнику',
  },
  {
    id: 424,
    en: 'approach',
    ua: 'підхід, наближення, наставання',
    context: 'this approach does not work',
    association: 'enemy mechs approaching',
  },
  {
    id: 425,
    en: 'bloatware',
    ua: 'вірус',
    context: '',
    association: 'напухша зовнішність',
  },
  {
    id: 426,
    en: 'dispatch',
    ua: 'відправлення, врегулювання',
    context: 'dispatch the action to reducer',
    association: 'диспетчер відправив потяг',
  },
  {
    id: 427,
    en: 'consistently',
    ua: 'послідовно',
    context: '',
    association: 'консистенція послідовності',
  },
  {
    id: 428,
    en: 'pattern',
    ua: 'зразок, викрійка, візерунок',
    context: '',
    association: '',
  },
  {
    id: 429,
    en: 'subdue',
    ua: 'підкоряти, подавляти',
    context: 'and quickly he`s subdude',
    association: 'підкорятися субординації',
  },
  {
    id: 430,
    en: 'disgrace',
    ua: 'ганьба',
    context: 'painted disgrace',
    association: 'не слава',
  },
  {
    id: 431,
    en: 'dub',
    ua: 'наректи, охрестити',
    context: 'dub thee unforgiven',
    association: 'нарікаю тебе дабом',
  },
  {
    id: 432,
    en: 'vow',
    ua: 'клятва, обіт, зарок',
    context: 'ooh, a vow unto his own',
    association: 'вау, клятва на крові',
  },
  {
    id: 433,
    en: 'struggle',
    ua: 'боротьба',
    context: 'the young man struggles on',
    association: 'стругал стовбур дерева для боротьби зі шкідниками',
  },
  {
    id: 434,
    en: 'deprive',
    ua: 'віднімати, забирати',
    context: 'deprived of all his thoughts',
    association: 'деприватизувати майно',
  },
  {
    id: 435,
    en: 'dedicate',
    ua: 'присвятити, віддатися',
    context: 'they dedicate they lives',
    association: 'присвятити себе дітям і котам',
  },
  {
    id: 436,
    en: 'whereas',
    ua: 'тоді як, оскільки',
    context: 'var is globally scoped whereas let and const are block scoped',
    association: 'де як',
  },
  {
    id: 437,
    en: 'following',
    ua: 'наступний',
    context: 'following example',
    association: 'послідувати',
  },
  {
    id: 438,
    en: 'represented',
    ua: 'представлений',
    context: '',
    association: 'реприза (вистава)',
  },
  {
    id: 439,
    en: 'interrelated',
    ua: 'взаємопов`язані',
    context: '',
    association: '',
  },
  {
    id: 440,
    en: 'rural',
    ua: 'сільський',
    context: '',
    association: 'russki sral v derevne',
  },
  {
    id: 441,
    en: 'hike',
    ua: 'похід, піший стрій',
    context: 'Installation complete! happy hiking!',
    association: 'хічхакер',
  },
  {
    id: 442,
    en: 'tackle',
    ua: 'зв`язати',
    context: '',
    association: 'таклі зв`язали',
  },
  {
    id: 443,
    en: 'descending',
    ua: 'спадання',
    context: 'in descending order',
    association: 'de-sending, децел',
  },
  {
    id: 444,
    en: 'doozy',
    ua: 'дурний',
    context: 'I know it`s a bit of a doozy',
    association: 'дузер (дурні будівельники з мапет шоу)',
  },
  {
    id: 445,
    en: 'superstition',
    ua: 'забобон, марновірство, ідолопоклонство',
    context: '',
    association: 'прихильники супермену (марновіри)',
  },
  {
    id: 446,
    en: 'facility',
    ua: 'уміння, здатність, легкість',
    context: '',
    association: 'уміння з легкістю фасувати',
  },
  {
    id: 447,
    en: 'compatibility',
    ua: 'сумісність',
    context: '',
    association: 'можливість скомпонувати різні сумісні компоненти',
  },
  {
    id: 448,
    en: 'divert',
    ua: 'відволікати, відхиляти',
    context: '',
    association: 'диверсифікація виробництва',
  },
  {
    id: 449,
    en: 'consecutive',
    ua: 'послідовний, наступний',
    context:
      'passwords that are greater than 5 characters long, and have two consecutive digits',
    association: 'після конца попереднього настає наступний',
  },
  {
    id: 450,
    en: 'charity',
    ua: 'благодійність',
    context: '',
    association: 'благодійні чари',
  },
  {
    id: 451,
    en: 'clarity',
    ua: 'прозорість, чистота, ясність',
    context: 'moment of clarity',
    association: 'Клара чиста і ясна прийшла з бані',
  },
  {
    id: 452,
    en: 'interchangeable',
    ua: 'взаємозамінюваний',
    context: 'the terms ECMAScript and JavaScript are interchangeable.',
    association: 'здібний до змін',
  },
  {
    id: 453,
    en: 'evolving',
    ua: 'розвиток',
    context: 'JavaScript is constantly evolving',
    association: 'еволюція',
  },
  {
    id: 454,
    en: 'altered',
    ua: 'змінено, змінений',
    context: 's will still point to the altered array',
    association: 'альтернативно',
  },
  {
    id: 455,
    en: 'concise',
    ua: 'лаконічний, стислий, конспективний',
    context: 'Use Arrow Functions to Write Concise Anonymous Functions',
    association: 'конспект повнорозмірний',
  },
  {
    id: 456,
    en: 'eliminate',
    ua: 'ліквідувати, знищувати, ігнорувати',
    context: 'The rest parameter eliminates the need to check the args array ',
    association: 'ліквідувати через ілюмінатор',
  },
  {
    id: 457,
    en: 'neatly',
    ua: 'акуратно, відточено, вправно, лаконічно',
    context: 'for neatly assigning values taken directly from an object',
    association: 'акуратно подивитись НЕТЛІ перешкод',
  },
  {
    id: 458,
    en: 'consequently',
    ua: 'отже, тож, тому',
    context:
      'Consequently, you cannot pick or choose which elements you want to assign to variables.',
    association: '',
  },
  {
    id: 459,
    en: 'involving',
    ua: 'залучення, зв`язування',
    context:
      'In some situations involving array destructuring, we might want to collect the rest of the elements into a separate array.',
    association: 'залучення зпідволі',
  },
  {
    id: 460,
    en: 'eradicate',
    ua: 'викорінювання',
    context: '',
    association: 'радикальне викорінювання',
  },
  {
    id: 461,
    en: 'although',
    ua: 'хоча, незважаючи на те що',
    context: '',
    association: 'алсо',
  },
  {
    id: 462,
    en: 'receipt',
    ua: 'квитанція, рецепт',
    context: '',
    association: 'рецепт',
  },
  {
    id: 463,
    en: 'comprehensive',
    ua: 'комплексний, всебічний, всеосяжний',
    context: '',
    association: 'компресорний комплекс',
  },
  {
    id: 464,
    en: 'rid',
    ua: 'позбутися, прибрати, викорчувати',
    context: 'Get rid of the stats, and see if you can destructure it.',
    association: 'рідагуючи - позбуваємось помилок',
  },
  {
    id: 465,
    en: 'robust',
    ua: 'надійний, міцний, здоровий, крутий',
    context:
      'This new way of creating strings gives you more flexibility to create robust strings.',
    association: 'надійна роба',
  },
  {
    id: 466,
    en: 'under the hood',
    ua: 'під капотом',
    context: '',
    association: 'під художествами',
  },
  {
    id: 467,
    en: 'instantiate',
    ua: 'створити екземпляр',
    context: 'using the new keyword to instantiate the object',
    association: 'новий екземпляр мене в інштаграмі',
  },
  {
    id: 468,
    en: 'implicit',
    ua: 'неявний, безумовний, те, що мається на увазі',
    context: 'then it is implicitly defined with no arguments',
    association: '',
  },
  {
    id: 469,
    en: 'precede',
    ua: 'передувати, бути попереду',
    context:
      'It is convention to precede the name of a private variable with an underscore (_).',
    association: 'спочатку присядь, а потім звертайся до чатланіна',
  },
  {
    id: 470,
    en: 'suppose',
    ua: 'припустимо, припущення',
    context: 'Suppose you have a file',
    association: 'припустимо, що існує суп з ос',
  },
  { id: 471, en: 'subtract', ua: 'відняти', context: '', association: '' },
  {
    id: 472,
    en: 'fallback',
    ua: 'відступати',
    context: 'fallback value',
    association: 'резервне значення',
  },
  {
    id: 473,
    en: 'fulfill',
    ua: 'виконувати, виповнити',
    context: 'you either fulfill your promise or fail to do so',
    association: 'повністю наповнити',
  },
  {
    id: 474,
    en: 'reckon',
    ua: 'розраховувати, нараховувати, покладатися',
    context: '',
    association: 'перерахувати, що в тебе на кону',
  },
  {
    id: 475,
    en: 'settled',
    ua: 'осіли, злагоджений, постійний, заселений',
    context: '',
    association: 'сидить осілий заселенець',
  },
  {
    id: 476,
    en: 'circumstances',
    ua: 'обставини',
    context: '',
    association: 'циркулюючі стани',
  },
  {
    id: 477,
    en: 'bewildered',
    ua: 'збентежений',
    context: '',
    association: 'будь одичалим',
  },
  {
    id: 478,
    en: 'distortion',
    ua: 'спотворення, деформація, перекручення',
    context: '',
    association: 'grunge tuned guitar with pedal',
  },
  {
    id: 479,
    en: 'considerate',
    ua: 'уважний, дбайливий, тактовний',
    context: '',
    association: 'розглядаючий',
  },
  {
    id: 480,
    en: 'intership',
    ua: 'стажування',
    context: '',
    association: 'інтернатура',
  },
  {
    id: 481,
    en: 'wildcard',
    ua: 'символ підстановки',
    context: 'you can save time using the wildcard character: .',
    association: 'дика картка',
  },
  {
    id: 482,
    en: 'vowel',
    ua: 'голосний звук',
    context: '',
    association: 'во велончелі присутні голосні звуки',
  },
  {
    id: 483,
    en: 'hyphen',
    ua: 'дефіс',
    context: 'hyphen character: -.',
    association: 'хайпова-курка пишеться через дефіс.',
  },
  {
    id: 484,
    en: 'sincere',
    ua: 'щирий',
    context: '',
    association: 'маючий сенс',
  },
  {
    id: 485,
    en: 'afterwards',
    ua: 'згодом, далі',
    context: '',
    association: 'після варти',
  },
  {
    id: 486,
    en: 'exposed',
    ua: 'піддається, викритий, виставлений',
    context: '',
    association: 'екс позиціонований (піддався на зміщення)',
  },
  {
    id: 487,
    en: 'equation',
    ua: 'рівняння',
    context: '',
    association: 'те що еквівалентне',
  },
  {
    id: 488,
    en: 'perservance',
    ua: 'наполегливість',
    context: 'the sound of perseverance',
    association: 'персона на сервері наполягає',
  },
  {
    id: 489,
    en: 'ascend',
    ua: 'зростання',
    context: 'ascending order',
    association: 'аскет зростає до багатія',
  },
  {
    id: 490,
    en: 'derive',
    ua: 'отримати, вивести, походити',
    context: 'derive result, getDerivedStateFromProps',
    association: 'посадиш зернятко отримаєш дерево',
  },
  {
    id: 491,
    en: 'tallie',
    ua: 'підрахунок',
    context: '',
    association: 'талія підраховує вартість жінки',
  },
  {
    id: 492,
    en: 'canvas',
    ua: 'полотно',
    context: '',
    association: 'Кличко всіх клав на канвас',
  },
  {
    id: 493,
    en: 'geek',
    ua: 'заучка, нерд, схиблений на чомусь, одержимий',
    context: 'geek news',
    association: 'geek i не тільки новини',
  },
  {
    id: 494,
    en: 'pace',
    ua: 'темп',
    context: '',
    association: 'пейси жида, який в темпі на всіх паразитує',
  },
  {
    id: 495,
    en: 'urgent',
    ua: 'терміновий, нагальний',
    context: '',
    association: 'терміновий ургант',
  },
  {
    id: 496,
    en: 'abyss',
    ua: 'безодня',
    context: 'welcome to my abyss',
    association: '',
  },
  {
    id: 497,
    en: 'abuse',
    ua: 'зловживання',
    context: '',
    association: 'над вживання',
  },
  {
    id: 498,
    en: 'caboose',
    ua: 'камбуз, гальмовий вагон',
    context: 'the last car on a train is the caboose',
    association: '',
  },
  {
    id: 499,
    en: 'nonetheless',
    ua: 'тим не менш, однак, все ж таки',
    context: 'however, it may be important to check for them nonetheless.',
    association: 'не це менше',
  },
  {
    id: 500,
    en: 'parceive',
    ua: 'сприймати, вбачати, відчувати',
    context: '',
    association: 'пересів, коли щось відчув',
  },
  {
    id: 501,
    en: 'flick',
    ua: 'рух, ривок',
    context: '',
    association: 'flixbus',
  },
  {
    id: 502,
    en: 'collision',
    ua: 'зіткнення, суперечність',
    context: '',
    association: 'колізія зіткнення',
  },
  { id: 503, en: 'glitch', ua: 'глюк', context: '', association: 'глючік' },
  {
    id: 504,
    en: 'assemble',
    ua: 'зібрати',
    context: '',
    association: 'асамблея (збір) ООН',
  },
  {
    id: 505,
    en: 'throughout',
    ua: 'всюди, повністю',
    context:
      'check points to see the status of your calculations throughout your code',
    association: 'сру аут всюди тут',
  },
  {
    id: 506,
    en: 'tend',
    ua: 'доглядати, прагнути',
    context: 'tends to happen',
    association: 'як правило трапляється, love me tender',
  },
  {
    id: 507,
    en: 'vice versa',
    ua: 'навпаки',
    context:
      'A potential issue is when variables either should be reinitialized, and aren`t, or vice versa.',
    association: 'висить ворса',
  },
  {
    id: 508,
    en: 'dread',
    ua: 'страшний',
    context: 'dreaded infinite loop.',
    association: 'страшний суддя дредд',
  },
  {
    id: 509,
    en: 'mayhem',
    ua: 'хаос, заподіяння каліцтва',
    context:
      'Infinite loops are likely to freeze or crash the browser, and cause general program execution mayhem',
    association: 'махнув на все рукою і почався хаос і каліцтво',
  },
  {
    id: 510,
    en: 'capable',
    ua: 'здатний, вдатний, вправний, тямущий',
    context: 'arrays are also capable of storing complex objects',
    association: 'могутній кеп',
  },
  {
    id: 511,
    en: 'comprise',
    ua: 'включати, обнімати, охоплювати, входити до складу',
    context: 'comprised of one or more element(s)',
    association: 'прийшов приз і ввійшов до складу всіх інших',
  },
  {
    id: 512,
    en: 'verbose',
    ua: 'багатослівний',
    context: 'that would have been more complex and more verbose',
    association: 'вербальний вербовник вербує кацапів на партизанські дії',
  },
  {
    id: 513,
    en: 'mapped',
    ua: 'зіставленні, співвіднесені',
    context:
      'In other words, they are pieces of data (values) mapped to unique identifiers called properties (keys)',
    association: 'мапед шоу - заставлене',
  },
  {
    id: 514,
    en: 'slightly',
    ua: 'ледь, трохи',
    context: 'a slightly more complex object',
    association: 'слега',
  },
  {
    id: 515,
    en: 'versatile',
    ua: 'універсальний, гнучкий, несталий',
    context: 'you will see even more versatile applications of objects.',
    association: 'гнучкий вершитель',
  },
  {
    id: 516,
    en: 'curriculum',
    ua: 'навчальний план, розклад',
    context: 'Prep section of the curriculum',
    association: 'кури килим з навчання',
  },
  {
    id: 517,
    en: 'clause',
    ua: 'пункт, артикул, стаття, (команда запиту)',
    context: 'clause SELECT',
    association: 'клоз(ет)',
  },
  {
    id: 518,
    en: 'timid',
    ua: 'боязкий, лячний',
    context: '',
    association: 'тіміті лячний',
  },
  {
    id: 519,
    en: 'absence',
    ua: 'відсутність',
    context: '',
    association: 'за сценою',
  },
  {
    id: 520,
    en: 'coward',
    ua: 'боягуз',
    context: '',
    association: 'Говард (воловіц) боягуз',
  },
  {
    id: 521,
    en: 'boot camp',
    ua: 'навчальний табір',
    context: '',
    association: 'табір де вчать взуватися',
  },
  {
    id: 522,
    en: 'confident(ce)',
    ua: 'впевнений, певний (впевненість)',
    context: '',
    association: 'впевнений в конфіденційності',
  },
  {
    id: 523,
    en: 'contrived',
    ua: 'надуманий',
    context: 'this example is a bit contrived',
    association: 'контр-думка під івою',
  },
  {
    id: 524,
    en: 'released',
    ua: 'звільнений, вийшов в прокат',
    context: 'movie released',
    association: 'реліз',
  },
  {
    id: 525,
    en: 'sluggish',
    ua: 'млявий, вайлуватий',
    context: 'app becomes sluggish for some reason',
    association: 'млявий салага',
  },
  {
    id: 526,
    en: 'tangible',
    ua: 'відчутний, матеріальний, реальний',
    context: 'objects: tangible things people can observe and interact with',
    association: 'те, що можна спробувати язиком',
  },
  {
    id: 527,
    en: 'blueprint',
    ua: 'креслення, проект',
    context: 'think of them as a blueprint for the creation of new objects',
    association: 'креслення на блакитному папері',
  },
  {
    id: 528,
    en: 'instance',
    ua: 'зразок, екземпляр, вимога, інстанція',
    context: 'create a new instance of class Dog',
    association: 'нова інстанція екземпляру',
  },
  {
    id: 529,
    en: 'hound',
    ua: 'гончак, пес, цькувати собаками',
    context: '',
    association: 'bloodhound dog',
  },
  {
    id: 530,
    en: 'aviary',
    ua: 'вольєр, пташник',
    context: 'thousands of different birds in an aviary',
    association: 'авіарій з пташками',
  },
  {
    id: 531,
    en: 'drastically',
    ua: 'різко, радикально, рішуче',
    context: '',
    association: 'різко як проноса (драстікалі)',
  },
  {
    id: 532,
    en: 'stand out',
    ua: 'виділятися, виставляти на показ, відходити',
    context: '',
    association: 'стяти поза чимось',
  },
  {
    id: 533,
    en: 'ramping',
    ua: 'нарощення, повзти, будувати рампу',
    context: '',
    association: 'рампувати',
  },
  {
    id: 534,
    en: 'embraces',
    ua: 'обійми',
    context: '',
    association: 'брас, наброситися з обіймами',
  },
  {
    id: 535,
    en: 'peek',
    ua: 'підглядати, пошук',
    context: 'peek a web design',
    association: 'Пікассо підглядав за натурницями',
  },
  {
    id: 536,
    en: 'regard(s)',
    ua: 'щодо, стосовно, (повага)',
    context: 'best regards',
    association: 'реєструю повагу щодо',
  },
  {
    id: 537,
    en: 'tedious',
    ua: 'нудний, неприємний, стомливий',
    context: 'this becomes tedious after more than a few properties',
    association: 'Тадеуш Шолто був нудним',
  },
  {
    id: 538,
    en: 'glide',
    ua: 'ковзати',
    context: 'a boat glides by the river',
    association: 'гладити ковзаюче хутро тварини',
  },
  {
    id: 539,
    en: 'alter',
    ua: 'змінювати',
    context: 'ALTER TABLE',
    association: 'альтер его',
  },
  {
    id: 540,
    en: 'expiration',
    ua: 'закінчення терміну дії',
    context: 'cookies expiration time is over',
    association: 'експлуатація',
  },
  {
    id: 541,
    en: 'expired',
    ua: 'закінчився',
    context: 'your trial period is expired',
    association: 'бувший період',
  },
  {
    id: 542,
    en: 'get rid',
    ua: 'позбався, збувати',
    context: 'get rid of the redundant curly braces',
    association: 'рідюсь свій код',
  },
  {
    id: 543,
    en: 'division',
    ua: 'поділ',
    context: 'div',
    association: 'дівчік',
  },
  {
    id: 544,
    en: 'pot',
    ua: 'горщик',
    context: '',
    association: 'потний поц сидить на горщику',
  },
  {
    id: 545,
    en: 'sequential',
    ua: 'послідовний',
    context: '',
    association: 'сіквел (після фільму)',
  },
  {
    id: 546,
    en: 'crunch',
    ua: 'хрускіт',
    context: '',
    association: 'кран чогось хрустить',
  },
  {
    id: 547,
    en: 'caption',
    ua: 'підпис',
    context: '',
    association: 'копчений підпис',
  },
  {
    id: 548,
    en: 'override',
    ua: 'перевизначити, відхиляти',
    context: 'override the variable',
    association: 'переосідлати',
  },
  {
    id: 549,
    en: 'constraint',
    ua: 'обмеження, примус',
    context: '',
    association: 'обмежені деталями конструктора',
  },
  {
    id: 550,
    en: 'constrain',
    ua: 'обмеження',
    context:
      'Dear Chasey LainI wrote to constrainThis letter is my lastAs your biggest fanI must demandYou let me eat your ass',
    association: 'ми не можемо вийти за обмеження конструкції',
  },
  {
    id: 551,
    en: 'convoluted',
    ua: 'заплутаний, звивистий, скручений спіраллю',
    context: '',
    association: 'закручена конвалюта пігулок',
  },
  {
    id: 552,
    en: 'secuentially',
    ua: 'послідовно',
    context: '',
    association: 'секунди ідуть послідовно одна за одною',
  },
  {
    id: 553,
    en: 'contribute',
    ua: 'сприяти',
    context: '',
    association: 'контрибуція прияє розвитку країни',
  },
  {
    id: 554,
    en: 'tidy',
    ua: 'охайний, у доброму стані',
    context: '',
    association: 'тайди вже поки ти ще в доброму стані',
  },
  {
    id: 555,
    en: 'generic',
    ua: 'загальний',
    context: 'Learn TypeScript Generics',
    association: 'генеральне прибирання',
  },
  {
    id: 556,
    en: 'interfering',
    ua: 'заважаючий',
    context: '',
    association: 'інтерференція сонячних промінів через те, що їм заважає',
  },
  {
    id: 557,
    en: 'appealing',
    ua: 'привабливий, покращений, благаючий',
    context: 'TailwindCSS helps to make appealing UI',
    association: 'привабливий гей, благаючий про апеляцію і суді',
  },
  {
    id: 558,
    en: 'processing',
    ua: 'обробка',
    context: 'reduce method allows for more general forms of array processing',
    association: 'процес обробки',
  },
  {
    id: 559,
    en: 'drawback',
    ua: 'недолік, перешкода',
    context:
      'documentation and semantic variable naming can help mitigate readability drawbacks',
    association: 'дробак',
  },
  {
    id: 560,
    en: 'mitigate',
    ua: 'пом`якшувати, зменшувати, полегшувати',
    context:
      'documentation and semantic variable naming can help mitigate readability drawbacks',
    association: 'зменшення воріт для мітингу (пом`якшення) настроїв',
  },
  {
    id: 561,
    en: 'flatten',
    ua: 'звід',
    context: 'flatten an array of arrays',
    association: 'звід з 10 квартир',
  },
  {
    id: 562,
    en: 'encourage',
    ua: 'заохочувати, підбадьорювати, підбурювати',
    context:
      'it is encouraged to provide a callback function to specify how to sort the array items',
    association: 'вводити в кураж',
  },
  {
    id: 563,
    en: 'delimiter',
    ua: 'роздільник',
    context: 'delimiter that is used to separate the array elements',
    association: 'делитель',
  },
  { id: 564, en: 'mature', ua: 'зрілий', context: '', association: 'материй' },
  {
    id: 565,
    en: 'aside',
    ua: 'вбік, поблизу',
    context: '',
    association: 'сторона',
  },
  {
    id: 566,
    en: 'circuit',
    ua: 'схема',
    context: '',
    association: 'сверкаюча схема',
  },
  {
    id: 567,
    en: 'intruder',
    ua: 'порушник, той хто вторгся до не своїх володінь',
    context: 'alarm! intruder in the house',
    association: 'порушник трудового кодексу',
  },
  {
    id: 568,
    en: 'polish',
    ua: 'полірувати, лиск',
    context: '',
    association: 'полижи язиком до блиску',
  },
  {
    id: 569,
    en: 'distribute',
    ua: 'поширення',
    context: '',
    association: 'дистрибуція',
  },
  {
    id: 570,
    en: 'exceed',
    ua: 'перевищувати',
    context: 'extra ceed (передача)',
    association: 'екстрена передача',
  },
  {
    id: 571,
    en: 'downward',
    ua: 'вниз',
    context: '',
    association: 'нижня палата',
  },
  {
    id: 572,
    en: 'amend',
    ua: 'змінювати, лагодити, виправляти',
    context: '',
    association: 'вносити зміни, після того, як сказали амінь',
  },
  {
    id: 573,
    en: 'harness',
    ua: 'упряж, запрягання',
    context: '',
    association: 'харі в упряжці',
  },
  {
    id: 574,
    en: 'justify',
    ua: 'виправдати, розрівнювати',
    context: 'justify-content',
    association: 'встановлювати правосуддя',
  },
  {
    id: 575,
    en: 'chirpe',
    ua: 'щебетати',
    context: '',
    association: 'чарпати, цвірінчати',
  },
  {
    id: 576,
    en: 'strand',
    ua: 'ланцюг, пасма',
    context: 'pairs of DNA strands consist of nucleobase pairs.',
    association: 'стрем`я ланцюгове',
  },
  {
    id: 577,
    en: 'assertion',
    ua: 'твердження',
    context: 'check the assertion tests for examples.',
    association: 'асоціативне твердження',
  },
  {
    id: 578,
    en: 'drawer',
    ua: 'ящик, шухляда',
    context: '',
    association: 'шухлядка з дрів',
  },
  {
    id: 579,
    en: 'envelope',
    ua: 'конверт',
    context: '',
    association: 'конверт з хабарем для ецилопу',
  },
  {
    id: 580,
    en: 'identation',
    ua: 'відступ (в абзаці), видовбування',
    context: 'I hate python because of the indentation',
    association: 'ідентифікувався і відступив від лібералів',
  },
  {
    id: 581,
    en: 'insufficient',
    ua: 'недостатній',
    context: '',
    association: 'інсульт від серцевої недостатності',
  },
  {
    id: 582,
    en: 'sufficient',
    ua: 'достатній, компетентний',
    context: '',
    association: 'суфлера достатньо для вистави',
  },
  {
    id: 583,
    en: 'likely',
    ua: 'ймовірно, можливо, підхоже',
    context: '',
    association: 'тебе лайкають, ймовірно ти подобаєшся',
  },
  {
    id: 584,
    en: 'hence',
    ua: 'отже',
    context: 'hance you`re a gay',
    association: 'отже хенсони (ммм-боп)',
  },
  {
    id: 585,
    en: 'broaden',
    ua: 'розширити, поширювати',
    context: '',
    association: 'розбродвеїти',
  },
  {
    id: 586,
    en: 'reliable',
    ua: 'надійний, солідний, вірогідний',
    context: '',
    association: 'надійне реле',
  },
  {
    id: 587,
    en: 'pesky',
    ua: 'докучливий, набридлий, огидний',
    context: '',
    association: 'докучливі песики',
  },
  {
    id: 588,
    en: 'disruptive',
    ua: 'руйнівний, підривний, розрядний',
    context: '',
    association: 'деструктивне руйнування',
  },
  {
    id: 589,
    en: 'leverage',
    ua: 'кредитне плече, система важелів, дія важелів',
    context: '',
    association: 'печінка на вагах',
  },
  {
    id: 590,
    en: 'insite',
    ua: 'прозорливість, розуміння, в полі зору',
    context: '',
    association: 'на сайті MDN приходить розуміння',
  },
  {
    id: 591,
    en: 'scraping',
    ua: 'вишкрібання, вискоблювання, дряпання',
    context: '',
    association: 'шкрябання скрапу',
  },
  {
    id: 592,
    en: 'conduct',
    ua: 'поведінка, вести, диригувати, керувати',
    context:
      'Behind the scenes, React Redux is using Redux`s store.dispatch() to conduct these dispatches with mapDispatchToProps().',
    association: 'кондуктор слідкує за поведінкою і веде бесіду з дережером',
  },
  {
    id: 593,
    en: 'plotting',
    ua: 'накреслення, замишляти змову, коїти',
    context: '',
    association: 'накреслити плот',
  },
  {
    id: 594,
    en: 'outlier',
    ua: 'викид, військова застава',
    context: '',
    association: 'лежить поза межами',
  },
  {
    id: 595,
    en: 'inconsistent',
    ua: 'непослідовний, мінливий',
    context: '',
    association: 'непослідовність дій приводить до не тої консистенції',
  },
  {
    id: 596,
    en: 'perseption',
    ua: 'сприйняття',
    context: '',
    association: 'персональне сприйняття',
  },
  {
    id: 597,
    en: 'anticipated',
    ua: 'очікуваний',
    context: '',
    association: 'привезли очікуваний антисептик',
  },
  {
    id: 598,
    en: 'token',
    ua: 'жетон, формальність, номінальний',
    context: 'Unexpected token `)`',
    association: 'синтаксис написання коду',
  },
  {
    id: 599,
    en: 'leisure',
    ua: 'дозвілля',
    context: '',
    association: 'лишився клопоту маю вільний час',
  },
  {
    id: 600,
    en: 'overdue',
    ua: 'прострочений, давно готовий, запізнілий',
    context: '',
    association: 'після часу роботи',
  },
  {
    id: 601,
    en: 'fare',
    ua: 'вартість проїзду, тариф, їжа, їздець',
    context: '',
    association: 'поферніть решту за проїзд',
  },
  {
    id: 602,
    en: 'internally',
    ua: 'внутрішньо, всередині, духовно',
    context: '',
    association: 'інтерни - внутрішні працівники',
  },
  {
    id: 603,
    en: 'genuinly',
    ua: 'щиро, природньо, непідробна',
    context: '',
    association: 'геніальна конгруентність',
  },
  {
    id: 604,
    en: 'obstacle',
    ua: 'перешкода, завада, запин',
    context: '',
    association: 'обставини підкидають перешкоди',
  },
  {
    id: 605,
    en: 'lettuce',
    ua: 'листя салату, салат',
    context: '',
    association: 'латук',
  },
  {
    id: 606,
    en: 'nibbling',
    ua: 'відкушування',
    context: '',
    association: 'ніблер з футурами (жуйка)',
  },
  {
    id: 607,
    en: 'appliance',
    ua: 'прилад, застосування',
    context: '',
    association: '',
  },
  { id: 608, en: 'witnesses', ua: 'свідки', context: '', association: '' },
  {
    id: 609,
    en: 'nifty',
    ua: 'витончений',
    context: '',
    association: 'витончена нефертіті',
  },
  {
    id: 610,
    en: 'moisture',
    ua: 'вологість',
    context: '',
    association: 'мойша вологий від мрій',
  },
  {
    id: 611,
    en: 'thus',
    ua: 'таким чином',
    context: 'Thus A ↔ N, B ↔ O and so on.',
    association: 'таким чином туз б`є все!',
  },
  {
    id: 612,
    en: 'inclined',
    ua: 'схильний, похилий',
    context: '',
    association: 'наклоненний',
  },
  {
    id: 613,
    en: 'fellow',
    ua: 'товариш, парубок, супутник',
    context: 'fellowship of the ring',
    association: 'філон нам не товариш',
  },
  {
    id: 614,
    en: 'simultaneously',
    ua: 'одночасно',
    context: '',
    association: 'симулятор тенісу (одночасної гри)',
  },
  {
    id: 615,
    en: 'ditch',
    ua: 'канава, рів, траншея',
    context: 'Ditch Custom CSS for Bootstrap',
    association: 'дичину викидаємо в канаву',
  },
  {
    id: 616,
    en: 'evenly',
    ua: 'рівномірно, гладко, однаково, порівну',
    context: 'evenly spread out across the page',
    association: 'рівномірний ливень',
  },
  {
    id: 617,
    en: 'intact',
    ua: 'непорушений, непошкоджений, цілий',
    context: 'leave your document ready function itself intact',
    association: 'поза тактом',
  },
  {
    id: 618,
    en: 'rejoice',
    ua: 'радіти',
    context: 'The world rejoices!',
    association: 'знову отримуючий задоволення',
  },
  {
    id: 619,
    en: 'guts',
    ua: 'нутрощі',
    context: 'You`ve got guts!',
    association: 'що ти маєш всередині',
  },
  {
    id: 620,
    en: 'beyond',
    ua: 'поза межами',
    context: 'To infinity and beyond!',
    association: 'бейонсе поза межами музики',
  },
  {
    id: 621,
    en: 'bullseye',
    ua: 'Яблучко!',
    context: 'Bullseye!',
    association: 'попасти в око бику',
  },
  {
    id: 622,
    en: 'rather',
    ua: 'швидше, вірніше, краще',
    context:
      'ES6 class component, rather than a stateless functional component?',
    association: 'на рафіку швидше, ніж пішки',
  },
  {
    id: 623,
    en: 'preface',
    ua: 'передмова, пролог',
    context: 'you preface the code that you use to access it with this.',
    association: 'перед обличчям чогось',
  },
  {
    id: 624,
    en: 'encore',
    ua: 'виклик на біс!',
    context: 'encore',
    association: 'анкор естчьо анкор!',
  },
  {
    id: 625,
    en: 'aware',
    ua: 'в курсі, обізнаний, свідомий',
    context: '',
    association: '',
  },
  {
    id: 626,
    en: 'batch',
    ua: 'група, партія, пачка, серія',
    context:
      'React may batch multiple state updates in order to improve performance.',
    association: 'гурт Йохана Себастяна Баха',
  },
  {
    id: 627,
    en: 'cumbersome',
    ua: 'незграбний, громіздкий',
    context:
      'This is not just cumbersome but also makes the code unnecessarily complicated.',
    association: 'Кембер був громіздким дядьком (німець)',
  },
  {
    id: 628,
    en: 'sloppy',
    ua: 'неохайний, забризканий, мокрий',
    context: '',
    association: 'злопав полуниці, заплямився і став неохайним',
  },
  {
    id: 629,
    en: 'hamper',
    ua: 'перешкоджати',
    context: '',
    association: 'хам перешкоджаючий навчвнню',
  },
  {
    id: 630,
    en: 'tuple',
    ua: 'кортеж',
    context:
      'A tuple is an immutable, ordered collection of elements, which can store values of different types',
    association: 'кортеж, довгий, як тополя',
  },
  {
    id: 631,
    en: 'acquare',
    ua: 'придбати, добувати, досягати',
    context: '',
    association: 'купити акваріум',
  },
  {
    id: 632,
    en: 'obituary',
    ua: 'некролог',
    context: '',
    association: 'перелік мертвих абітурієнтів',
  },
  {
    id: 633,
    en: 'obscure',
    ua: 'незрозумілий, відлюдний, невиразний',
    context: '',
    association: 'обкурений незрозумілий тип',
  },
  {
    id: 634,
    en: 'flaw',
    ua: 'недолік, дефект, прогалина',
    context: 'flawless victory',
    association: 'дефективний флавій захотів Клеопатру',
  },
  {
    id: 635,
    en: 'apart',
    ua: 'окремо, на віддалі, відособлено',
    context: 'we never fall in love we only fall apart',
    association: 'окремий апарат для фото',
  },
  {
    id: 636,
    en: 'approve',
    ua: 'схвалювати, затверджувати',
    context: 'Even grumpy cat approves!',
    association: 'а правда підтверджується',
  },
  {
    id: 637,
    en: 'transpile',
    ua: 'трансформація і компіляція',
    context:
      'Transpiling, short for transformation and compiling, refers to the process of converting source code from one programming language into another',
    association: '',
  },
  {
    id: 638,
    en: 'prosper',
    ua: 'процвітати, досягати успіхів, бути сприятливим',
    context: 'Code long and prosper',
    association: 'успішні люди живуть на проспектах',
  },
  {
    id: 639,
    en: 'lift-off',
    ua: 'відрив від землі',
    context: 'we have lift-off',
    association: 'ліфт вийшов',
  },
  {
    id: 640,
    en: 'enforce',
    ua: 'примушувати',
    context:
      'Redux does not enforce state immutability, however, you are responsible for enforcing it in the code of your reducer functions.',
    association: 'застосування сили',
  },
  {
    id: 641,
    en: 'temptate',
    ua: 'спокуса',
    context: 'may be tempting to divide state into multiple pieces',
    association: '',
  },
  {
    id: 642,
    en: 'tend',
    ua: 'прагнути, доглядати',
    context:
      'because actions usually originate from some user interaction and tend to carry some data with them',
    association: 'гарний тендер прагне зусиль',
  },
  {
    id: 643,
    en: 'cereals',
    ua: 'крупи',
    context: '',
    association: 'крупи під серіали',
  },
  { id: 644, en: 'footage', ua: 'кадри', context: '', association: 'фотожки' },
  {
    id: 645,
    en: 'thereby',
    ua: 'таким чином',
    context: 'thereby extracting the local state into the Redux store',
    association: 'таким чином теребей став фіндіром',
  },
  {
    id: 646,
    en: 'adjacent',
    ua: 'суміжний, сусідній',
    context: 'Adjacent JSX elements must be wrapped in an enclosing tag.',
    association: 'А Джейсон Нюстед був суміжний з Metallica',
  },
  {
    id: 647,
    en: 'invitation',
    ua: 'запрошення, зазив',
    context: '',
    association: 'запрошую на інвайт',
  },
  {
    id: 648,
    en: 'exalted',
    ua: 'піднесений, величний',
    context: '',
    association: 'екзальтований',
  },
  {
    id: 649,
    en: 'consistent',
    ua: 'послідовний, відповідний',
    context: '',
    association: 'консистенція послідовності',
  },
  {
    id: 650,
    en: 'persuasive',
    ua: 'переконливий, довідний',
    context: '',
    association: 'персвасивив сам себе',
  },
  {
    id: 651,
    en: 'negotiable',
    ua: 'договірна, доступний, прохідний',
    context: '',
    association: 'неГоша нам доступний, а Гоша - ні…',
  },
  {
    id: 652,
    en: 'pros and cons',
    ua: 'плюси і мінуси',
    context: 'pros and cons of TS',
    association: '',
  },
  {
    id: 653,
    en: 'intend',
    ua: 'мають намір',
    context: '',
    association: 'інтесивно готуватися щось зробити',
  },
  {
    id: 654,
    en: 'overwhelm',
    ua: 'переповнювати, вражати, закидувати',
    context: '',
    association: 'овер вельмишановний переповнений шаною',
  },
  {
    id: 655,
    en: 'captivate',
    ua: 'захоплювати, брати в полон',
    context: '',
    association: 'каптіва захоплює багато грошей на бензин',
  },
  {
    id: 656,
    en: 'tailored web pages',
    ua: 'адаптовані веб сторінки',
    context: '',
    association: 'стів тайлер адаптувався до аєросмит',
  },
  {
    id: 657,
    en: 'insult',
    ua: 'образа, виклик, нападати',
    context: 'it is insults you',
    association: 'напав образливий інсульт',
  },
  {
    id: 658,
    en: 'facilitate',
    ua: 'сприяти, полегшувати',
    context: '',
    association: 'Фасилій полегшував взаємодію з ФЕС',
  },
  {
    id: 659,
    en: 'entity',
    ua: 'сутність, буття, існування',
    context: '',
    association: 'вся суть IN TITTY',
  },
  {
    id: 660,
    en: 'permanent',
    ua: 'постійний, безповоротний',
    context: '',
    association:
      'перманентна (постійна) революція по всіх країнах світу була зупинена.',
  },
  {
    id: 661,
    en: 'sniff',
    ua: 'нюхати, вдихання',
    context: 'sniff my stinky socks',
    association: 'нюхальний сніг (кокс)',
  },
  {
    id: 662,
    en: 'reliy(es)',
    ua: 'покладатися, сподіватися',
    context: '',
    association: 'релігія покладається на Бога',
  },
  {
    id: 663,
    en: 'stir',
    ua: 'перемішати, ворушіння, метушня',
    context: '',
    association: 'Стірліц влаштував метушню в гестапо',
  },
  {
    id: 664,
    en: 'readly',
    ua: 'з легкістю',
    context: '',
    association: 'рідлі скот з легкістю зняв Прометея (alien)',
  },
  {
    id: 665,
    en: 'prerequisite',
    ua: 'передумова',
    context: '',
    association: 'пре реквізити до отримання паспорту',
  },
  {
    id: 666,
    en: 'crucial',
    ua: 'вирішальне значення, критичний, поворотний',
    context: 'exception is a crucial concept in programming',
    association: 'в куршавелі зечмо отримало вирішальне значення',
  },
  {
    id: 667,
    en: 'vulnerability',
    ua: 'вразливість',
    context: '',
    association: 'коли вулнуєшся - ти особливо вразливий',
  },
  {
    id: 668,
    en: 'primarily',
    ua: 'в першу чергу, спершу, спочатку',
    context: '',
    association: 'спочатку приморили зечмо, а потім врятували Україну',
  },
  {
    id: 669,
    en: 'incorporate',
    ua: 'включати, об`єднання, сполучати',
    context: '',
    association: 'damage inc.',
  },
  {
    id: 670,
    en: 'entry',
    ua: 'запис, вступ, вхід',
    context: '',
    association: 'запис застосовується після натиснення Enter',
  },
  {
    id: 671,
    en: 'detached',
    ua: 'відокремлений, відірваний, незалежний',
    context: 'semi-detached',
    association: 'не до торканий',
  },
  {
    id: 672,
    en: 'workarounds',
    ua: 'обхідні шляхи',
    context: 'workarounds for common issues',
    association: 'робота навколо (небезпеки)',
  },
  {
    id: 673,
    en: 'judicious',
    ua: 'розважливий',
    context: '',
    association: 'жидівский розважливий ребе',
  },
  {
    id: 674,
    en: 'subtleties',
    ua: 'тонкощі',
    context: '',
    association: 'шатлові дрібниці',
  },
  {
    id: 675,
    en: 'mate',
    ua: 'товариш',
    context: 'I have a site about my groupmates',
    association: 'материй товариш',
  },
  {
    id: 676,
    en: 'tip',
    ua: 'порада, підказка, чайові',
    context: 'have you any tips for me?',
    association: 'типові настанови',
  },
  {
    id: 677,
    en: 'acquainted',
    ua: 'знайомий',
    context: '',
    association: 'хочучий задати запитання після ознайомлення',
  },
  {
    id: 678,
    en: 'purge',
    ua: 'чистка',
    context: 'vagetables purge the body',
    association: 'пурген',
  },
  {
    id: 679,
    en: 'soot',
    ua: 'сажа, копоть, нагар',
    context: '',
    association: 'сутінки як сажа',
  },
  {
    id: 680,
    en: 'nook',
    ua: 'закуток',
    context: '',
    association: 'занукався в куточок',
  },
  {
    id: 681,
    en: 'bead',
    ua: 'бісер, крапля, кулька',
    context: '',
    association: 'біде для крапель дзюрива',
  },
  {
    id: 682,
    en: 'dime',
    ua: 'копійки',
    context:
      'My rhymes score dimes ain`t nothing you can doIt`s hard to clap with your dick in your hand, dude',
    association: 'дай мені копійку',
  },
  {
    id: 683,
    en: 'implied',
    ua: 'мається на увазі',
    context: '',
    association: 'імплантат - мається на увазі, що то справжній зуб',
  },
  {
    id: 684,
    en: 'tertiary',
    ua: 'третинний',
    context: 'tertiary colors',
    association: 'тертий сир на 3 частини',
  },
  {
    id: 685,
    en: 'saturation',
    ua: 'насиченість',
    context: 'hsl',
    association: 'насиченість Сатурну газами',
  },
  {
    id: 686,
    en: 'hue',
    ua: 'відтінок',
    context: 'hsl',
    association: 'хью грант відтіняє інших зірок',
  },
  {
    id: 687,
    en: 'reconciliation',
    ua: 'злагодження',
    context: 'more simple ajusting (reconciliation) of app',
    association: 'ре-консолідація',
  },
  {
    id: 688,
    en: 'opaque',
    ua: 'непрозорий',
    context: 'a solid wall is opaque, and no light can pass through',
    association: 'країни ОПЕК мають не прозору діяльність',
  },
  {
    id: 689,
    en: 'sleeve',
    ua: 'рукав (зливний)',
    context: '',
    association: 'зливний рукав, ковпачок для зливу пасти з ручки',
  },
  {
    id: 690,
    en: 'harsh',
    ua: 'суворий, жорсткий, різкий',
    context:
      'The black color of your border looks pretty harsh against the more transparent sleeve.',
    association: 'різкий харч в кацапську пику',
  },
  {
    id: 691,
    en: 'spruce',
    ua: 'чепуритись',
    context: 'you can spruce it up',
    association: 'чопорний спрут',
  },
  {
    id: 692,
    en: 'brittle',
    ua: 'крихкий',
    context: 'the test is brittle, it is easy to break',
    association: 'крихка брітні спірс',
  },
  {
    id: 693,
    en: 'fallback',
    ua: 'відступати, обходити',
    context: 'we use this fallback',
    association: 'впасти назад',
  },
  {
    id: 694,
    en: 'ridiculous',
    ua: 'смішний, сміхотворний',
    context: 'library names is ridiculous',
    association: 'смішний ридикюль (жіноча сумочка)',
  },
  {
    id: 695,
    en: 'right away',
    ua: 'зараз',
    context: 'and right away we`ll start',
    association: 'she said come over right away © the offspring',
  },
  {
    id: 696,
    en: 'presumably',
    ua: 'імовірно',
    context: 'presumably after fetcing some data we use screen.findBy...',
    association: 'при сумі ймовірно буде більше число',
  },
  {
    id: 697,
    en: 'feasible',
    ua: 'можливо',
    context: 'it is more feasible',
    association: 'фізично можливо',
  },
  {
    id: 698,
    en: 'intercept',
    ua: 'перехопити',
    context: 'the library is going to intercept the request',
    association: 'ввійти і заціпити',
  },
  {
    id: 699,
    en: 'preliminary',
    ua: 'попередній',
    context: 'preliminary kind of testing purposes',
    association: 'перед лімітом',
  },
  {
    id: 700,
    en: 'narrow down',
    ua: 'звузити',
    context: 'narrow down the margins of problem',
    association: 'опустити вузьке ще нижче, тобто чим нижче, тим вужче',
  },
  {
    id: 701,
    en: 'inference',
    ua: 'висновок',
    context: 'type inference',
    association: 'інфернальний висновок',
  },
  {
    id: 702,
    en: 'annotation',
    ua: 'коментар, примітка, тлумачення',
    context: 'type annotation',
    association: 'анотація',
  },
  {
    id: 703,
    en: 'what the heck',
    ua: 'якого біса',
    context: '',
    association: 'який хек, нам треба скумбрія!',
  },
  {
    id: 704,
    en: 'inquire',
    ua: 'запитати',
    context: '',
    association: 'рекувайр - перезапит, квайр - запит',
  },
  {
    id: 705,
    en: 'flip back',
    ua: 'повернути назад',
    context: 'I`ll flip back over to my browser.',
    association: 'flip back - чювак ета репчік',
  },
  {
    id: 706,
    en: 'mesh',
    ua: 'сітка',
    context: 'mesh TS together with frameworks',
    association: 'мішок',
  },
  {
    id: 707,
    en: 'exacerbate',
    ua: 'загострювати',
    context: 'exacerbated by the type definition file',
    association: 'загострення на екзамені/співбесіді',
  },
  {
    id: 708,
    en: 'wire up',
    ua: 'підключити',
    context: 'wire up our session',
    association: '',
  },
  {
    id: 709,
    en: 'darn good',
    ua: 'чортівскі добре',
    context: 'it`s pretty darn good',
    association: 'драні шкарпетки штопаю',
  },
  {
    id: 710,
    en: 'bloated',
    ua: 'роздутий, жирний, пихатий',
    context: 'it`s pretty bloated',
    association: 'жирний до блювачки',
  },
  {
    id: 711,
    en: 'downside',
    ua: 'мінус',
    context: 'downside of this approach',
    association: 'нижній бік',
  },
  {
    id: 712,
    en: 'waive',
    ua: 'відмовлятися',
    context: '',
    association: 'покачати головою',
  },
  {
    id: 713,
    en: 'prone',
    ua: 'схильний',
    context: 'can be inconvenient and prone to typing errors',
    association: 'схильний до порно',
  },
  {
    id: 714,
    en: 'conjunction',
    ua: 'сполучник, з`єднання',
    context: 'used in conjunction with the TodoList component',
    association: 'коньяк зв`язує людей',
  },
  {
    id: 715,
    en: 'intimidate',
    ua: 'залякати',
    context: 'HOCs might seem intimidating at first',
    association: 'мене лякає інтим з Брітні Спірс',
  },
  {
    id: 716,
    en: 'itinerary',
    ua: 'маршрут',
    context: 'All routes provided will have non-empty itineraries',
    association: 'іді нерарі',
  },
  {
    id: 717,
    en: 'sparingly',
    ua: 'економно',
    context:
      'Apply it sparingly because it makes component reuse more difficult',
    association: 'в спарингу - заощаджуй енергію.',
  },
  {
    id: 718,
    en: 'caveat',
    ua: 'застереження',
    context: '',
    association: 'каві - ніт',
  },
  {
    id: 719,
    en: 'intricacies',
    ua: 'хитросплетіння',
    context: 'intricacies of web development',
    association: 'інтриги',
  },
  {
    id: 720,
    en: 'milestone',
    ua: 'віха',
    context: 'Congratulations for the milestone!',
    association: 'камінь, який показує що ми здолали милю.',
  },
  {
    id: 721,
    en: 'shuffle',
    ua: 'перетасувати',
    context: 'Shuffle the Array Instead of Generating Random Indices',
    association: 'суфле - перемішані яєчні жовтки.',
  },
  {
    id: 722,
    en: 'spade',
    ua: 'піка (масть)',
    context: 'The Ace of Spades',
    association: 'спайдермен заходить з піки',
  },
  {
    id: 723,
    en: 'clubs',
    ua: 'трефа (масть)',
    context: 'I know what the clubs are weapons of war',
    association: 'трефовий клуб',
  },
  {
    id: 724,
    en: 'conceal',
    ua: 'приховувати',
    context: 'he may conceal a king in his heand',
    association: 'steal and conceal',
  },
  {
    id: 725,
    en: 'admit',
    ua: 'визнати',
    context: 'James Hetfield admitted that he steal songs from himself',
    association: 'відмітити ',
  },
  {
    id: 726,
    en: 'dump',
    ua: 'звалище, скидати',
    context: 'mongodump creates dump from the MongoDB db',
    association: 'дам по дупі і вилетиш на сміття',
  },
  {
    id: 727,
    en: 'contingencies',
    ua: 'непередбачувані витрати',
    context: 'there are many contingencies in the new project',
    association: 'непередбачено куплене печіво конті',
  },
  {
    id: 728,
    en: 'irritating',
    ua: 'дратує',
    context: 'stop it! this irritating me',
    association: 'іридій дратує своєю сріблястість',
  },
  {
    id: 729,
    en: 'preceding',
    ua: 'попередній',
    context: 'describe the termdefined by the preceding <dt>',
    association: 'присів-встав попередник зайняв твоє місце',
  },
  {
    id: 730,
    en: 'slug',
    ua: 'слимак, вайло, лінуватися',
    context: 'don`t wanna be a slug - it`s cool to hate!',
    association: 'млявий слуга',
  },
  {
    id: 731,
    en: 'dormant',
    ua: 'сплячий, бездіяльний',
    context: 'dormant property of application',
    association: 'дармові бездіяльні працівники',
  },
  {
    id: 732,
    en: 'vague',
    ua: 'розпливчатий, не визначений, імлистий, не чіткий',
    context: 'vague target - doesn`t work',
    association: 'вагаючийся кліент',
  },
  {
    id: 733,
    en: 'mangling',
    ua: 'калічення',
    context: 'mangling properties',
    association: 'чоловік під глінтвейном калічиться на лижах',
  },
  {
    id: 734,
    en: 'compelling',
    ua: 'переконливий, нездоланний, непереборний',
    context: 'compelling explanation',
    association: 'комплексне пояснення переконує більше',
  },
  {
    id: 735,
    en: 'constrain',
    ua: 'обмеження',
    context:
      'Dear Chasey LainI wrote to constrainThis letter is my lastAs your biggest fanI must demandYou let me eat your ass',
    association: 'ми не можемо вийти за обмеження конструкції',
  },
];

export default dbEn;

//const dbEn = [];
