const dbJp = [
  { id: 1, jp: 'watashi [вата́ші]', ua: 'Я', context: '', association: '' },
  { id: 2, jp: 'anata [ана́та]', ua: 'Ти', context: '', association: '' },
  { id: 3, jp: 'kare [каре́]', ua: 'Він', context: '', association: '' },
  { id: 4, jp: 'kanojo [кано́дзьо]', ua: 'Вона', context: '', association: '' },
  {
    id: 5,
    jp: 'watashitachi [вата́шітачі]',
    ua: 'Ми',
    context: '',
    association: '',
  },
  {
    id: 6,
    jp: 'anatatachi [ана́та тачі]',
    ua: 'Ви',
    context: '',
    association: '',
  },
  { id: 7, jp: 'iku [і́ку]', ua: 'Йти', context: '', association: '' },
  { id: 8, jp: 'kuru [ку́ру]', ua: 'Приходити', context: '', association: '' },
  { id: 9, jp: 'taberu [табе́ру]', ua: 'Їсти', context: '', association: '' },
  { id: 10, jp: 'nomu [но́му]', ua: 'Пити', context: '', association: '' },
  { id: 11, jp: 'aisuru [а́йсуру]', ua: 'Любити', context: '', association: '' },
  { id: 12, jp: 'miru [мі́ру]', ua: 'Бачити', context: '', association: '' },
  { id: 13, jp: 'yomu [йо́му]', ua: 'Читати', context: '', association: '' },
  { id: 14, jp: 'kaku [ка́ку]', ua: 'Писати', context: '', association: '' },
  {
    id: 15,
    jp: 'hanasu [хана́су]',
    ua: 'Говорити',
    context: '',
    association: '',
  },
  {
    id: 16,
    jp: 'rikaisuru [ріка́йсуру]',
    ua: 'Розуміти',
    context: '',
    association: '',
  },
  { id: 17, jp: 'hoshii [хоші́]', ua: 'Хотіти', context: '', association: '' },
  {
    id: 18,
    jp: 'hitsuyou [хіцу́йо]',
    ua: 'Потребувати',
    context: '',
    association: '',
  },
  { id: 19, jp: 'dekiru [де́кіру]', ua: 'Могти', context: '', association: '' },
  {
    id: 20,
    jp: 'shinakereba naranai [шінаке́реба нарана́й]',
    ua: 'Мусити',
    context: '',
    association: '',
  },
  {
    id: 21,
    jp: 'shitsumonsuru [шіцу́монсуру]',
    ua: 'Питати',
    context: '',
    association: '',
  },
  {
    id: 22,
    jp: 'kotaeru [кота́еру]',
    ua: 'Відповідати',
    context: '',
    association: '',
  },
  { id: 23, jp: 'sagasu [сага́су]', ua: 'Шукати', context: '', association: '' },
  {
    id: 24,
    jp: 'tsukuru [цуку́ру]',
    ua: 'Робити',
    context: '',
    association: '',
  },
  { id: 25, jp: 'omou [омо́у]', ua: 'Думати', context: '', association: '' },
  { id: 26, jp: 'oshieru [о́шієру]', ua: 'Вчити', context: '', association: '' },
  {
    id: 27,
    jp: 'narau [нара́у]',
    ua: 'Навчатися',
    context: '',
    association: '',
  },
  { id: 28, jp: 'okiru [окі́ру]', ua: 'Вставати', context: '', association: '' },
  { id: 29, jp: 'neru [не́ру]', ua: 'Спати', context: '', association: '' },
  {
    id: 30,
    jp: 'aru [а́ру]',
    ua: 'Бути (про неживе)',
    context: '',
    association: '',
  },
  {
    id: 31,
    jp: 'iru [і́ру]',
    ua: 'Бути (про живе)',
    context: '',
    association: '',
  },
  { id: 32, jp: 'kau [ка́у]', ua: 'Купувати', context: '', association: '' },
  { id: 33, jp: 'uru [у́ру]', ua: 'Продавати', context: '', association: '' },
  { id: 34, jp: 'matsu [ма́цу]', ua: 'Чекати', context: '', association: '' },
  { id: 35, jp: 'hashiru [хаші́ру]', ua: 'Бігти', context: '', association: '' },
  { id: 36, jp: 'oyogu [о́йоґу]', ua: 'Плавати', context: '', association: '' },
  { id: 37, jp: 'asobu [асо́бу]', ua: 'Грати', context: '', association: '' },
  { id: 38, jp: 'kiku [кі́ку]', ua: 'Слухати', context: '', association: '' },
  {
    id: 39,
    jp: 'manabu [мана́бу]',
    ua: 'Вивчати',
    context: '',
    association: '',
  },
  {
    id: 40,
    jp: 'tsukau [цука́у]',
    ua: 'Використовувати',
    context: '',
    association: '',
  },
  {
    id: 41,
    jp: 'tsukeru [цуке́ру]',
    ua: 'Вмикати',
    context: '',
    association: '',
  },
  { id: 42, jp: 'kesu [ке́су]', ua: 'Вимикати', context: '', association: '' },
  { id: 43, jp: 'kiru [кі́ру]', ua: 'Різати', context: '', association: '' },
  {
    id: 44,
    jp: 'shimeru [шіме́ру]',
    ua: 'Закривати',
    context: '',
    association: '',
  },
  {
    id: 45,
    jp: 'akeru [аке́ру]',
    ua: 'Відкривати',
    context: '',
    association: '',
  },
  {
    id: 46,
    jp: 'noru [но́ру]',
    ua: 'Сідати в транспорт',
    context: '',
    association: '',
  },
  {
    id: 47,
    jp: 'oriru [орі́ру]',
    ua: 'Виходити з транспорту',
    context: '',
    association: '',
  },
  { id: 48, jp: 'kiru [кі́ру]', ua: 'Одягати', context: '', association: '' },
  { id: 49, jp: 'nugu [ну́ґу]', ua: 'Знімати', context: '', association: '' },
  {
    id: 50,
    jp: 'hanareru [хана́ре́ру]',
    ua: 'Відходити',
    context: '',
    association: '',
  },
  {
    id: 51,
    jp: 'wasureru [васу́ре́ру]',
    ua: 'Забувати',
    context: '',
    association: '',
  },
  {
    id: 52,
    jp: 'oboeru [обо́еру]',
    ua: 'Запам`ятовувати',
    context: '',
    association: '',
  },
  {
    id: 53,
    jp: 'omoidashimasu [омоідашіма́су]',
    ua: 'Згадувати',
    context: '',
    association: '',
  },
  {
    id: 54,
    jp: 'tsukeru [цуке́ру]',
    ua: 'Причіплювати',
    context: '',
    association: '',
  },
  { id: 55, jp: 'hairu [ха́іру]', ua: 'Входити', context: '', association: '' },
  { id: 56, jp: 'deru [де́ру]', ua: 'Виходити', context: '', association: '' },
  {
    id: 57,
    jp: 'norikaeru [норіка́еру]',
    ua: 'Пересідати',
    context: '',
    association: '',
  },
  { id: 58, jp: 'kiku [кі́ку]', ua: 'Запитувати', context: '', association: '' },
  {
    id: 59,
    jp: 'wakaru [вака́ру]',
    ua: 'Розуміти',
    context: '',
    association: '',
  },
  { id: 60, jp: 'shiru [ші́ру]', ua: 'Знати', context: '', association: '' },
  {
    id: 61,
    jp: 'wakarimasen [вака́ріма́сен]',
    ua: 'Не розуміти',
    context: '',
    association: '',
  },
  {
    id: 62,
    jp: 'tsukareru [цукара́ре́ру]',
    ua: 'Втомлюватися',
    context: '',
    association: '',
  },
  {
    id: 63,
    jp: 'isogu [ісо́ґу]',
    ua: 'Поспішати',
    context: '',
    association: '',
  },
  { id: 64, jp: 'dekiru [де́кіру]', ua: 'Вміти', context: '', association: '' },
  {
    id: 65,
    jp: 'tsudzuku [цуцу́дуку]',
    ua: 'Продовжувати',
    context: '',
    association: '',
  },
  {
    id: 66,
    jp: 'owaru [ова́ру]',
    ua: 'Закінчувати',
    context: '',
    association: '',
  },
  {
    id: 67,
    jp: 'hajimaru [хаджима́ру]',
    ua: 'Починатися',
    context: '',
    association: '',
  },
  {
    id: 68,
    jp: 'takai [така́ї]',
    ua: 'Високий / Дорогий',
    context: '',
    association: '',
  },
  { id: 69, jp: 'hikui [хіку́ї]', ua: 'Низький', context: '', association: '' },
  { id: 70, jp: 'atsui [ацу́ї]', ua: 'Гарячий', context: '', association: '' },
  { id: 71, jp: 'samui [саму́ї]', ua: 'Холодний', context: '', association: '' },
  { id: 72, jp: 'ookii [о́окі]', ua: 'Великий', context: '', association: '' },
  {
    id: 73,
    jp: 'chiisai [чііса́ї]',
    ua: 'Маленький',
    context: '',
    association: '',
  },
  {
    id: 74,
    jp: 'atarashii [атараші́ї]',
    ua: 'Новий',
    context: '',
    association: '',
  },
  { id: 75, jp: 'furui [фуру́ї]', ua: 'Старий', context: '', association: '' },
  {
    id: 76,
    jp: 'arigatou [аріґато́у]',
    ua: 'Дякую',
    context: '',
    association: '',
  },
  {
    id: 77,
    jp: 'dou itashimashite [до́у іташіма́шіте]',
    ua: 'Будь ласка',
    context: '',
    association: '',
  },
  {
    id: 78,
    jp: 'sumimasen [сумімасе́н]',
    ua: 'Вибачте',
    context: '',
    association: '',
  },
  {
    id: 79,
    jp: 'gomen nasai [ґоме́н наса́й]',
    ua: 'Перепрошую',
    context: '',
    association: '',
  },
  {
    id: 80,
    jp: 'ohayou gozaimasu [о́ха́йо ґо́заїма́су]',
    ua: 'Доброго ранку',
    context: '',
    association: '',
  },
  {
    id: 81,
    jp: 'konnichiwa [конні́чіва]',
    ua: 'Добрий день',
    context: '',
    association: '',
  },
  {
    id: 82,
    jp: 'konbanwa [конба́нва]',
    ua: 'Добрий вечір',
    context: '',
    association: '',
  },
  {
    id: 83,
    jp: 'oyasuminasai [оясу́мінаса́й]',
    ua: 'На добраніч',
    context: '',
    association: '',
  },
  { id: 84, jp: 'hai [хай]', ua: 'Так', context: '', association: '' },
  { id: 85, jp: 'iie [і́є]', ua: 'Ні', context: '', association: '' },
  {
    id: 86,
    jp: 'wakarimasu [вака́ріма́су]',
    ua: 'Розумію',
    context: '',
    association: '',
  },
  {
    id: 87,
    jp: 'onegaishimasu [онеґа́йшіма́су]',
    ua: 'Прошу (будь ласка)',
    context: '',
    association: '',
  },
  {
    id: 88,
    jp: 'douzo [до́узо]',
    ua: 'Прошу (візьміть)',
    context: '',
    association: '',
  },
  {
    id: 89,
    jp: 'ikura desu ka [і́кура де́су ка]',
    ua: 'Скільки коштує?',
    context: '',
    association: '',
  },
  {
    id: 90,
    jp: 'doko desu ka [до́ко де́су ка]',
    ua: 'Де знаходиться?',
    context: '',
    association: '',
  },
  {
    id: 91,
    jp: 'nan desu ka [нан де́су ка]',
    ua: 'Що це?',
    context: '',
    association: '',
  },
  {
    id: 92,
    jp: 'o-genki desu ka [о-ґе́нкі де́су ка]',
    ua: 'Як справи?',
    context: '',
    association: '',
  },
  {
    id: 93,
    jp: 'genki desu [ґе́нкі де́су]',
    ua: 'Все добре',
    context: '',
    association: '',
  },
  {
    id: 94,
    jp: 'mata ne [мата́ не]',
    ua: 'До побачення (неформальне)',
    context: '',
    association: '',
  },
  {
    id: 95,
    jp: 'tadaima [тада́іма]',
    ua: 'Я вдома',
    context: '',
    association: '',
  },
  {
    id: 96,
    jp: 'itterasshai [іттерасша́й]',
    ua: 'Щасливої дороги',
    context: '',
    association: '',
  },
  {
    id: 97,
    jp: 'okaerinasai [окаерінаса́й]',
    ua: 'Ласкаво просимо назад',
    context: '',
    association: '',
  },
  {
    id: 98,
    jp: 'itadakimasu [ітадакіма́су]',
    ua: 'Смачного (перед їжею)',
    context: '',
    association: '',
  },
  {
    id: 99,
    jp: 'gochisousama [ґочісо́усама]',
    ua: 'Дякую за їжу',
    context: '',
    association: '',
  },
];

console.log(dbJp[0]); //
export default dbJp;

// const dbJp = [];
